import { describe, it, expect } from 'vitest'
import { generateCaddyfile } from '../../../../src/runtime/bootstrap/index.js'

describe('generateCaddyfile — global block', () => {
  it('starts with the GENERATED warning header', () => {
    const out = generateCaddyfile({ email: 'ops@example.com', sites: [] })
    expect(out).toMatch(/^# GENERATED by groundflare/)
  })

  it('includes the ACME contact email in the global block', () => {
    const out = generateCaddyfile({ email: 'ops@example.com', sites: [] })
    expect(out).toContain('email ops@example.com')
  })

  it('uses Let\'s Encrypt by default (no acme_ca line unless overridden)', () => {
    const out = generateCaddyfile({ email: 'ops@example.com', sites: [] })
    expect(out).not.toContain('acme_ca')
  })

  it('emits acme_ca when specified (e.g. for staging)', () => {
    const out = generateCaddyfile({
      email: 'ops@example.com',
      sites: [],
      acmeCa: 'https://acme-staging-v02.api.letsencrypt.org/directory',
    })
    expect(out).toContain('acme_ca https://acme-staging-v02.api.letsencrypt.org/directory')
  })

  it('emits `admin off` when adminAddress is null', () => {
    const out = generateCaddyfile({
      email: 'ops@example.com',
      sites: [],
      adminAddress: null,
    })
    expect(out).toContain('admin off')
  })

  it('emits `admin <address>` when adminAddress is set', () => {
    const out = generateCaddyfile({
      email: 'ops@example.com',
      sites: [],
      adminAddress: 'localhost:2020',
    })
    expect(out).toContain('admin localhost:2020')
  })

  it('enables persist_config by default', () => {
    const out = generateCaddyfile({ email: 'ops@example.com', sites: [] })
    expect(out).toContain('persist_config on')
  })

  it('omits persist_config when explicitly disabled', () => {
    const out = generateCaddyfile({
      email: 'ops@example.com',
      sites: [],
      persistConfig: false,
    })
    expect(out).not.toContain('persist_config')
  })
})

describe('generateCaddyfile — site blocks', () => {
  const base = {
    email: 'ops@example.com',
    sites: [
      { hostname: 'api.example.com', upstream: '127.0.0.1:8080' },
      { hostname: 'admin.example.com', upstream: '127.0.0.1:8080' },
    ],
  }

  it('creates one block per site with the hostname as label', () => {
    const out = generateCaddyfile(base)
    expect(out).toContain('api.example.com {')
    expect(out).toContain('admin.example.com {')
  })

  it('reverse_proxy directive points at the configured upstream', () => {
    const out = generateCaddyfile(base)
    expect(out).toContain('reverse_proxy 127.0.0.1:8080')
  })

  it('enables gzip + zstd encoding by default', () => {
    const out = generateCaddyfile(base)
    expect(out).toContain('encode gzip zstd')
  })

  it('omits encode when the site opts out', () => {
    const out = generateCaddyfile({
      email: 'ops@example.com',
      sites: [
        { hostname: 'raw.example.com', upstream: '127.0.0.1:8080', encode: false },
      ],
    })
    // Still have a block, just no encode line
    expect(out).toContain('raw.example.com {')
    expect(out).not.toMatch(/^\s*encode /m)
  })

  it('emits JSON log block directed at stdout', () => {
    const out = generateCaddyfile(base)
    expect(out).toContain('log {')
    expect(out).toContain('output stdout')
    expect(out).toContain('format json')
  })

  it('appends extra directives verbatim inside a site block', () => {
    const out = generateCaddyfile({
      email: 'ops@example.com',
      sites: [
        {
          hostname: 'api.example.com',
          upstream: '127.0.0.1:8080',
          extra: ['header -Server', 'rate_limit 100r/s'],
        },
      ],
    })
    expect(out).toContain('header -Server')
    expect(out).toContain('rate_limit 100r/s')
  })

  it('works with an empty sites list (global block only)', () => {
    const out = generateCaddyfile({ email: 'ops@example.com', sites: [] })
    expect(out).toContain('{')
    expect(out).toContain('}')
    expect(out).not.toContain('reverse_proxy')
  })
})

describe('generateCaddyfile — validation', () => {
  it('rejects missing/invalid email', () => {
    expect(() => generateCaddyfile({ email: '', sites: [] })).toThrow(/email/)
    expect(() => generateCaddyfile({ email: 'not-an-email', sites: [] })).toThrow(/email/)
    expect(() => generateCaddyfile({ email: 'a@', sites: [] })).toThrow(/email/)
    expect(() => generateCaddyfile({ email: '@a.com', sites: [] })).toThrow(/email/)
    expect(() => generateCaddyfile({ email: 'a@b@c', sites: [] })).toThrow(/email/)
    expect(() => generateCaddyfile({ email: 'a@b', sites: [] })).toThrow(/email/)
  })

  it('rejects invalid hostnames', () => {
    expect(() =>
      generateCaddyfile({
        email: 'ops@example.com',
        sites: [{ hostname: '', upstream: '127.0.0.1:8080' }],
      }),
    ).toThrow(/hostname/)
    expect(() =>
      generateCaddyfile({
        email: 'ops@example.com',
        sites: [{ hostname: '-invalid.com', upstream: '127.0.0.1:8080' }],
      }),
    ).toThrow(/hostname/)
  })

  it('rejects invalid upstreams', () => {
    expect(() =>
      generateCaddyfile({
        email: 'ops@example.com',
        sites: [{ hostname: 'api.example.com', upstream: '' }],
      }),
    ).toThrow(/upstream/)
    expect(() =>
      generateCaddyfile({
        email: 'ops@example.com',
        sites: [{ hostname: 'api.example.com', upstream: 'has spaces' }],
      }),
    ).toThrow(/upstream/)
  })
})
