import { describe, it, expect } from 'vitest'
import {
  cronUnitName,
  generateCronUnitPair,
  generateWorkerSystemdUnit,
} from '../../../../src/runtime/bootstrap/index.js'

function parseIni(text: string): Record<string, string[]> {
  // Micro INI parser for systemd-style units (no value splitting; duplicates kept).
  const sections: Record<string, string[]> = {}
  let section = ''
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue
    if (line.startsWith('[') && line.endsWith(']')) {
      section = line.slice(1, -1)
      sections[section] = sections[section] ?? []
      continue
    }
    if (section) sections[section]!.push(line)
  }
  return sections
}

describe('generateWorkerSystemdUnit — defaults', () => {
  const out = generateWorkerSystemdUnit({
    capnpPath: '/var/lib/groundflare/system/worker.capnp',
  })

  it('starts with a GENERATED warning', () => {
    expect(out).toMatch(/^# GENERATED by groundflare/)
  })

  it('declares [Unit] with Description + After', () => {
    const s = parseIni(out)
    expect(s.Unit).toContain('Description=groundflare workerd runtime')
    expect(s.Unit).toContain('After=network.target')
  })

  it('runs as the groundflare user/group', () => {
    const s = parseIni(out)
    expect(s.Service).toContain('User=groundflare')
    expect(s.Service).toContain('Group=groundflare')
  })

  it('uses the default workerd binary and capnp path', () => {
    const s = parseIni(out)
    expect(s.Service).toContain(
      'ExecStart=/usr/local/bin/workerd serve /var/lib/groundflare/system/worker.capnp',
    )
  })

  it('applies the default resource caps (80% mem, 80% cpu, 1024 tasks, 65536 nofile)', () => {
    const s = parseIni(out)
    expect(s.Service).toContain('MemoryMax=80%')
    expect(s.Service).toContain('CPUQuota=80%')
    expect(s.Service).toContain('TasksMax=1024')
    expect(s.Service).toContain('LimitNOFILE=65536')
  })

  it('restarts on failure with 5s cooldown', () => {
    const s = parseIni(out)
    expect(s.Service).toContain('Restart=on-failure')
    expect(s.Service).toContain('RestartSec=5')
  })

  it('sends stdout and stderr to journald', () => {
    const s = parseIni(out)
    expect(s.Service).toContain('StandardOutput=journal')
    expect(s.Service).toContain('StandardError=journal')
    expect(s.Service).toContain('SyslogIdentifier=groundflare-worker')
  })

  it('points EnvironmentFile at the default location', () => {
    const s = parseIni(out)
    expect(s.Service).toContain('EnvironmentFile=/etc/groundflare/environment')
  })

  it('installs to multi-user.target', () => {
    const s = parseIni(out)
    expect(s.Install).toContain('WantedBy=multi-user.target')
  })
})

describe('generateWorkerSystemdUnit — overrides', () => {
  it('honours a custom description', () => {
    const out = generateWorkerSystemdUnit({
      capnpPath: '/tmp/w.capnp',
      description: 'groundflare workspace "prod-us"',
    })
    expect(out).toContain('Description=groundflare workspace "prod-us"')
  })

  it('honours custom user and working directory', () => {
    const out = generateWorkerSystemdUnit({
      capnpPath: '/tmp/w.capnp',
      user: 'workerd',
      group: 'workerd',
      workingDirectory: '/opt/workerd',
    })
    expect(out).toContain('User=workerd')
    expect(out).toContain('Group=workerd')
    expect(out).toContain('WorkingDirectory=/opt/workerd')
  })

  it('allows disabling the EnvironmentFile via null', () => {
    const out = generateWorkerSystemdUnit({
      capnpPath: '/tmp/w.capnp',
      environmentFile: null,
    })
    expect(out).not.toContain('EnvironmentFile=')
  })

  it('honours a custom environment file path', () => {
    const out = generateWorkerSystemdUnit({
      capnpPath: '/tmp/w.capnp',
      environmentFile: '/etc/app.env',
    })
    expect(out).toContain('EnvironmentFile=/etc/app.env')
  })

  it('appends extraServiceLines verbatim', () => {
    const out = generateWorkerSystemdUnit({
      capnpPath: '/tmp/w.capnp',
      extraServiceLines: ['NoNewPrivileges=yes', 'ProtectSystem=strict'],
    })
    expect(out).toContain('NoNewPrivileges=yes')
    expect(out).toContain('ProtectSystem=strict')
  })

  it('allows alternate restart policy', () => {
    const out = generateWorkerSystemdUnit({
      capnpPath: '/tmp/w.capnp',
      restart: 'always',
      restartSec: 30,
    })
    expect(out).toContain('Restart=always')
    expect(out).toContain('RestartSec=30')
  })
})

describe('generateWorkerSystemdUnit — validation', () => {
  it('rejects memory percent outside (0, 100]', () => {
    expect(() =>
      generateWorkerSystemdUnit({ capnpPath: '/tmp/w.capnp', memoryMaxPercent: 0 }),
    ).toThrow(/memoryMaxPercent/)
    expect(() =>
      generateWorkerSystemdUnit({ capnpPath: '/tmp/w.capnp', memoryMaxPercent: 101 }),
    ).toThrow(/memoryMaxPercent/)
    expect(() =>
      generateWorkerSystemdUnit({ capnpPath: '/tmp/w.capnp', memoryMaxPercent: -5 }),
    ).toThrow(/memoryMaxPercent/)
  })

  it('rejects cpu percent outside (0, 100]', () => {
    expect(() =>
      generateWorkerSystemdUnit({ capnpPath: '/tmp/w.capnp', cpuQuotaPercent: 0 }),
    ).toThrow(/cpuQuotaPercent/)
  })

  it('floors fractional percents to integer systemd values', () => {
    const out = generateWorkerSystemdUnit({
      capnpPath: '/tmp/w.capnp',
      memoryMaxPercent: 42.7,
    })
    expect(out).toContain('MemoryMax=42%')
  })
})

describe('cronUnitName', () => {
  it('produces a stable, short, prefixed name', () => {
    const name = cronUnitName('api', '*/5 * * * *')
    expect(name).toMatch(/^groundflare-cron-api-[0-9a-f]{8}$/)
  })

  it('is deterministic for the same inputs', () => {
    expect(cronUnitName('api', '*/5 * * * *')).toBe(cronUnitName('api', '*/5 * * * *'))
  })

  it('differs when the worker name differs', () => {
    expect(cronUnitName('api', '*/5 * * * *')).not.toBe(
      cronUnitName('admin', '*/5 * * * *'),
    )
  })

  it('differs when the cron expression differs', () => {
    expect(cronUnitName('api', '*/5 * * * *')).not.toBe(
      cronUnitName('api', '*/10 * * * *'),
    )
  })
})

describe('generateCronUnitPair — timer unit', () => {
  const pair = generateCronUnitPair({
    workerName: 'api',
    cronExpression: '*/5 * * * *',
  })

  it('embeds the translated OnCalendar value', () => {
    expect(pair.timer).toContain('OnCalendar=*-*-* *:0/5:00')
  })

  it('describes the worker + expression in Description=', () => {
    expect(pair.timer).toContain('Description=groundflare cron: api @ */5 * * * *')
  })

  it('enables Persistent=true by default', () => {
    expect(pair.timer).toContain('Persistent=true')
  })

  it('references its own .service via Unit=', () => {
    expect(pair.timer).toContain(`Unit=${pair.unitName}.service`)
  })

  it('installs into timers.target', () => {
    expect(pair.timer).toContain('WantedBy=timers.target')
  })

  it('uses default AccuracySec=1s', () => {
    expect(pair.timer).toContain('AccuracySec=1s')
  })

  it('honours persistent=false', () => {
    const p = generateCronUnitPair({
      workerName: 'api',
      cronExpression: '0 0 * * *',
      persistent: false,
    })
    expect(p.timer).toContain('Persistent=false')
  })

  it('honours a custom accuracy value', () => {
    const p = generateCronUnitPair({
      workerName: 'api',
      cronExpression: '0 0 * * *',
      accuracy: '10s',
    })
    expect(p.timer).toContain('AccuracySec=10s')
  })
})

describe('generateCronUnitPair — service unit', () => {
  const pair = generateCronUnitPair({
    workerName: 'api',
    cronExpression: '*/5 * * * *',
  })

  it('is a Type=oneshot service', () => {
    expect(pair.service).toContain('Type=oneshot')
  })

  it('requires the groundflare-worker.service by default', () => {
    expect(pair.service).toContain('Requires=groundflare-worker.service')
    expect(pair.service).toContain('After=groundflare-worker.service')
  })

  it('ExecStarts a curl POST to the default /__scheduled endpoint', () => {
    expect(pair.service).toContain('curl')
    expect(pair.service).toContain('--request POST')
    expect(pair.service).toContain('http://127.0.0.1:8080/__scheduled')
    expect(pair.service).toContain('worker=api')
  })

  it('URL-encodes the cron expression in the query string', () => {
    // encodeURIComponent passes `*` through but escapes `/` as %2F
    // and spaces as %20. `*/5 * * * *` becomes `*%2F5%20*%20*%20*%20*`.
    expect(pair.service).toContain('cron=*%2F5')
    expect(pair.service).toContain('%20')
    // sanity — raw unescaped spaces would break the systemd ExecStart line
    expect(pair.service).not.toContain('cron=*/5 ')
  })

  it('sends stdout + stderr to journald with a worker-tagged identifier', () => {
    expect(pair.service).toContain('StandardOutput=journal')
    expect(pair.service).toContain('StandardError=journal')
    expect(pair.service).toContain(`SyslogIdentifier=${pair.unitName}`)
  })

  it('honours a custom scheduledEndpoint and requiresUnit', () => {
    const p = generateCronUnitPair({
      workerName: 'api',
      cronExpression: '0 * * * *',
      scheduledEndpoint: 'http://127.0.0.1:9000/internal/scheduled',
      requiresUnit: 'groundflare-worker@prod.service',
    })
    expect(p.service).toContain('http://127.0.0.1:9000/internal/scheduled')
    expect(p.service).toContain('Requires=groundflare-worker@prod.service')
  })
})

describe('generateCronUnitPair — validation', () => {
  it('rejects invalid worker names', () => {
    expect(() =>
      generateCronUnitPair({ workerName: 'NotLower', cronExpression: '* * * * *' }),
    ).toThrow(/worker name/)
    expect(() =>
      generateCronUnitPair({ workerName: 'name_with_underscore', cronExpression: '* * * * *' }),
    ).toThrow(/worker name/)
  })

  it('propagates UnsupportedCronError from cronToSystemdCalendar', () => {
    expect(() =>
      generateCronUnitPair({ workerName: 'api', cronExpression: 'nope' }),
    ).toThrow(/Unsupported cron/)
  })
})
