import { describe, it, expect } from 'vitest'
import {
  collectRouterInfo,
  generateRouterJs,
  routerBindingName,
} from '../../../../src/runtime/workspace/index.js'
import type { WorkspaceWorker } from '../../../../src/runtime/workspace/index.js'

function worker(
  name: string,
  opts: Partial<WorkspaceWorker> = {},
): WorkspaceWorker {
  return {
    name,
    entryPath: `workers/${name}/code/current/index.js`,
    ...opts,
  }
}

describe('routerBindingName', () => {
  it('uppercases the worker name and prefixes WORKER_', () => {
    expect(routerBindingName('api')).toBe('WORKER_API')
  })

  it('replaces hyphens with underscores', () => {
    expect(routerBindingName('api-gateway')).toBe('WORKER_API_GATEWAY')
  })

  it('works for multi-hyphen names', () => {
    expect(routerBindingName('a-b-c')).toBe('WORKER_A_B_C')
  })
})

describe('collectRouterInfo', () => {
  it('splits workers into routable (with domain) and all', () => {
    const workers = [
      worker('a', { domain: 'a.example.com' }),
      worker('b'),
      worker('c', { domain: 'c.example.com' }),
    ]
    const info = collectRouterInfo(workers)
    expect(info.routableWorkers.map((w) => w.name)).toEqual(['a', 'c'])
    expect(info.allWorkers).toHaveLength(3)
  })

  it('handles empty input', () => {
    const info = collectRouterInfo([])
    expect(info.routableWorkers).toEqual([])
    expect(info.allWorkers).toEqual([])
  })
})

describe('generateRouterJs', () => {
  it('produces a leading "GENERATED" comment so humans see the warning', () => {
    expect(generateRouterJs([])).toMatch(/^\/\/ GENERATED by groundflare/)
  })

  it('declares a ROUTES object mapping domain → binding', () => {
    const js = generateRouterJs([
      worker('api', { domain: 'api.example.com' }),
      worker('admin', { domain: 'admin.example.com' }),
    ])
    expect(js).toContain('"api.example.com": "WORKER_API"')
    expect(js).toContain('"admin.example.com": "WORKER_ADMIN"')
  })

  it('lowercases domains before insertion into ROUTES', () => {
    const js = generateRouterJs([worker('api', { domain: 'API.Example.COM' })])
    expect(js).toContain('"api.example.com": "WORKER_API"')
  })

  it('declares CRON_BINDINGS for every worker (even without a domain)', () => {
    const js = generateRouterJs([
      worker('api', { domain: 'api.example.com' }),
      worker('internal'), // no domain, scheduled via cron only
    ])
    expect(js).toContain('CRON_BINDINGS')
    expect(js).toContain('"internal": "WORKER_INTERNAL"')
  })

  it('exports a default object with a fetch handler', () => {
    const js = generateRouterJs([worker('x', { domain: 'x.test' })])
    expect(js).toMatch(/export default \{/)
    expect(js).toMatch(/async fetch\(/)
  })

  it('includes an internal /__scheduled dispatch path (not as a tenant route)', () => {
    const js = generateRouterJs([worker('x', { domain: 'x.test' })])
    expect(js).toContain('/__scheduled')
    expect(js).toContain('dispatchScheduled')
  })

  it('returns 404 when no host matches', () => {
    const js = generateRouterJs([])
    expect(js).toContain(', 404')
    expect(js).toContain('no Worker matches host')
  })

  it('returns 503 when ROUTES has a match but the binding is missing', () => {
    // Defensive path — should be impossible in practice, but the router
    // handles it gracefully rather than throwing.
    const js = generateRouterJs([worker('x', { domain: 'x.test' })])
    expect(js).toContain(', 503')
    expect(js).toContain('target binding missing')
  })

  it('is deterministic for equivalent inputs', () => {
    const ws = [
      worker('a', { domain: 'a.test' }),
      worker('b', { domain: 'b.test' }),
    ]
    expect(generateRouterJs(ws)).toBe(generateRouterJs(ws))
  })
})

describe('generated router body — executes correctly in V8', () => {
  // Smoke test: actually evaluate the generated JS in a sandbox and invoke
  // its dispatch. If the generator produces invalid JS, this test crashes
  // loudly. We rewrite `export default { ... }` to `return { ... }` so the
  // whole module body (including ROUTES + CRON_BINDINGS consts at top) runs
  // inside a Function and the returned object closes over them.
  function loadRouter(workers: WorkspaceWorker[]): {
    fetch: (req: Request, env: Record<string, unknown>, ctx: unknown) => Promise<Response>
  } {
    const source = generateRouterJs(workers)
    const body = source.replace(/export default (\{[\s\S]*\})\s*$/, 'return $1')
    expect(body, 'router source must contain `export default {...}`').not.toBe(source)
    const factory = new Function('Response', 'URL', body)
    return factory(Response, URL) as ReturnType<typeof loadRouter>
  }

  it('dispatches to the correct tenant binding by Host header', async () => {
    const router = loadRouter([worker('api', { domain: 'api.example.com' })])
    let called: string | null = null
    const env = {
      WORKER_API: {
        fetch: async (req: Request): Promise<Response> => {
          called = new URL(req.url).pathname
          return new Response('ok')
        },
      },
    }
    const response = await router.fetch(
      new Request('https://api.example.com/foo'),
      env,
      {},
    )
    expect(response.status).toBe(200)
    expect(called).toBe('/foo')
  })

  it('normalizes request hostname to lowercase', async () => {
    const router = loadRouter([worker('api', { domain: 'api.example.com' })])
    const env = {
      WORKER_API: { fetch: async () => new Response('ok') },
    }
    const response = await router.fetch(
      new Request('https://API.EXAMPLE.COM/'),
      env,
      {},
    )
    expect(response.status).toBe(200)
  })

  it('returns 404 for unknown host', async () => {
    const router = loadRouter([worker('api', { domain: 'api.example.com' })])
    const response = await router.fetch(
      new Request('https://other.example.com/'),
      {},
      {},
    )
    expect(response.status).toBe(404)
    expect(await response.text()).toContain('no Worker matches host')
  })

  describe('internal /__scheduled dispatch', () => {
    it('routes POST /__scheduled?worker=<name>&cron=<expr> to the target scheduled handler', async () => {
      const router = loadRouter([worker('cleaner')])
      // Use an array collector to side-step TS control-flow narrowing
      // of a `let received = null` captured in an async callback.
      const events: Array<{ cron?: string; scheduledTime?: number }> = []
      const env = {
        WORKER_CLEANER: {
          scheduled: async (e: { cron?: string; scheduledTime?: number }) => {
            events.push(e)
          },
        },
      }
      const url = 'http://127.0.0.1:8080/__scheduled?worker=cleaner&cron=0+*+*+*+*'
      const response = await router.fetch(new Request(url, { method: 'POST' }), env, {})
      expect(response.status).toBe(200)
      expect(await response.text()).toBe('ok')
      expect(events).toHaveLength(1)
      expect(events[0]?.cron).toBe('0 * * * *')
      expect(typeof events[0]?.scheduledTime).toBe('number')
      // Event only — no env/ctx passed across the boundary (workerd would
      // reject ServiceStub serialization without the experimental flag).
      expect(Object.keys(events[0] ?? {}).sort()).toEqual(['cron', 'scheduledTime'])
    })

    it('returns 404 when __scheduled is reached via a non-localhost hostname', async () => {
      const router = loadRouter([worker('cleaner')])
      const env = { WORKER_CLEANER: { scheduled: async () => {} } }
      const response = await router.fetch(
        new Request('https://api.example.com/__scheduled?worker=cleaner&cron=a', {
          method: 'POST',
        }),
        env,
        {},
      )
      expect(response.status).toBe(404)
    })

    it('returns 405 on non-POST methods for __scheduled', async () => {
      const router = loadRouter([worker('cleaner')])
      const response = await router.fetch(
        new Request('http://127.0.0.1:8080/__scheduled?worker=cleaner'),
        { WORKER_CLEANER: { scheduled: async () => {} } },
        {},
      )
      expect(response.status).toBe(405)
      expect(response.headers.get('allow')).toBe('POST')
    })

    it('returns 400 when worker query param is missing', async () => {
      const router = loadRouter([worker('cleaner')])
      const response = await router.fetch(
        new Request('http://127.0.0.1:8080/__scheduled', { method: 'POST' }),
        { WORKER_CLEANER: { scheduled: async () => {} } },
        {},
      )
      expect(response.status).toBe(400)
    })

    it('returns 404 when the target worker name is not registered', async () => {
      const router = loadRouter([worker('cleaner')])
      const response = await router.fetch(
        new Request('http://127.0.0.1:8080/__scheduled?worker=ghost', {
          method: 'POST',
        }),
        { WORKER_CLEANER: { scheduled: async () => {} } },
        {},
      )
      expect(response.status).toBe(404)
      expect(await response.text()).toContain('ghost')
    })

    it('returns 404 when the target has no scheduled handler', async () => {
      const router = loadRouter([worker('cleaner')])
      const response = await router.fetch(
        new Request('http://127.0.0.1:8080/__scheduled?worker=cleaner', {
          method: 'POST',
        }),
        // No scheduled method on the target
        { WORKER_CLEANER: {} },
        {},
      )
      expect(response.status).toBe(404)
    })

    it('does not dispatch tenant fetch() for /__scheduled on a tenant host', async () => {
      const router = loadRouter([worker('api', { domain: 'api.test' })])
      let called = false
      const env = {
        WORKER_API: {
          fetch: async () => {
            called = true
            return new Response('ok')
          },
        },
      }
      const response = await router.fetch(
        new Request('https://api.test/__scheduled', { method: 'POST' }),
        env,
        {},
      )
      expect(response.status).toBe(404)
      expect(called).toBe(false)
    })
  })

  // ─── /__health ───────────────────────────────────────────────────

  describe('/__health', () => {
    it('returns 200 JSON with status=ok and the configured version', async () => {
      const source = generateRouterJs(
        [worker('api', { domain: 'api.test' })],
        { version: '0.6.2' },
      )
      const body = source.replace(/export default (\{[\s\S]*\})\s*$/, 'return $1')
      const factory = new Function('Response', 'URL', body)
      const router = factory(Response, URL) as {
        fetch: (req: Request, env: unknown, ctx: unknown) => Promise<Response>
      }

      const response = await router.fetch(
        new Request('http://any.host/__health'),
        {},
        {},
      )
      expect(response.status).toBe(200)
      expect(response.headers.get('content-type')).toMatch(/application\/json/)
      const payload = (await response.json()) as {
        status: string
        uptime_seconds: number
        version: string
      }
      expect(payload.status).toBe('ok')
      expect(payload.version).toBe('0.6.2')
      expect(Number.isFinite(payload.uptime_seconds)).toBe(true)
    })

    it('defaults version to "unknown" when not supplied', async () => {
      const router = loadRouter([])
      const response = await router.fetch(
        new Request('http://whatever/__health'),
        {},
        {},
      )
      const payload = (await response.json()) as { version: string }
      expect(payload.version).toBe('unknown')
    })

    it('is answered before the tenant dispatch — never leaks /__health to a worker', async () => {
      const router = loadRouter([worker('api', { domain: 'api.test' })])
      let called = false
      const env = {
        WORKER_API: {
          fetch: async () => {
            called = true
            return new Response('leaked')
          },
        },
      }
      const response = await router.fetch(
        new Request('https://api.test/__health'),
        env,
        {},
      )
      expect(response.status).toBe(200)
      expect(called).toBe(false)
    })
  })

  // ─── /__metrics ──────────────────────────────────────────────────

  describe('/__metrics', () => {
    it('requires loopback hostname — external Host returns 404', async () => {
      const router = loadRouter([worker('api', { domain: 'api.test' })])
      const response = await router.fetch(
        new Request('https://api.test/__metrics'),
        {},
        {},
      )
      expect(response.status).toBe(404)
    })

    it('serves Prometheus text on loopback', async () => {
      const router = loadRouter([worker('api', { domain: 'api.test' })])
      const response = await router.fetch(
        new Request('http://127.0.0.1:8080/__metrics'),
        {},
        {},
      )
      expect(response.status).toBe(200)
      expect(response.headers.get('content-type')).toMatch(
        /text\/plain; version=0\.0\.4/,
      )
      const text = await response.text()
      expect(text).toContain('# HELP groundflare_worker_requests_total')
      expect(text).toContain('# TYPE groundflare_worker_requests_total counter')
      expect(text).toContain('# HELP groundflare_worker_request_duration_seconds')
      expect(text).toContain('# HELP groundflare_worker_errors_total')
    })

    it('records a request+status_class counter after a tenant dispatch', async () => {
      const router = loadRouter([worker('api', { domain: 'api.test' })])
      const env = {
        WORKER_API: {
          fetch: async () => new Response('ok', { status: 200 }),
        },
      }
      await router.fetch(new Request('https://api.test/a'), env, {})
      await router.fetch(new Request('https://api.test/b'), env, {})

      const metrics = await router
        .fetch(new Request('http://127.0.0.1:8080/__metrics'), {}, {})
        .then((r) => r.text())

      expect(metrics).toMatch(
        /groundflare_worker_requests_total\{status_class="2xx",worker="api"\} 2/,
      )
      expect(metrics).toContain(
        'groundflare_worker_request_duration_seconds_count{worker="api"} 2',
      )
    })

    it('records an error counter when the tenant handler throws', async () => {
      const router = loadRouter([worker('api', { domain: 'api.test' })])
      const env = {
        WORKER_API: {
          fetch: async () => {
            throw new Error('boom')
          },
        },
      }
      await expect(
        router.fetch(new Request('https://api.test/'), env, {}),
      ).rejects.toThrow(/boom/)

      const metrics = await router
        .fetch(new Request('http://127.0.0.1:8080/__metrics'), {}, {})
        .then((r) => r.text())

      expect(metrics).toMatch(
        /groundflare_worker_errors_total\{kind="uncaught",worker="api"\} 1/,
      )
      // The thrown request still counts as a 5xx in the request total.
      expect(metrics).toMatch(
        /groundflare_worker_requests_total\{status_class="5xx",worker="api"\} 1/,
      )
    })

    it('labels metrics with the user-facing worker name, not the binding', async () => {
      const router = loadRouter([worker('api-gateway', { domain: 'x.test' })])
      const env = {
        WORKER_API_GATEWAY: {
          fetch: async () => new Response('ok'),
        },
      }
      await router.fetch(new Request('https://x.test/'), env, {})
      const metrics = await router
        .fetch(new Request('http://127.0.0.1:8080/__metrics'), {}, {})
        .then((r) => r.text())
      expect(metrics).toContain('worker="api-gateway"')
      expect(metrics).not.toContain('worker="WORKER_API_GATEWAY"')
    })
  })
})
