/**
 * Caddyfile generator.
 *
 * Caddy terminates TLS, handles Let's Encrypt ACME, emits JSON access logs
 * to journald, and reverse-proxies every configured domain to a single
 * upstream — the workerd router socket. The router worker itself decides
 * which tenant answers.
 *
 * See design/workspaces.md for the routing model (Caddy → workerd :8080
 * → Router Worker → tenant service bindings).
 */

export interface CaddyR2PublicRoute {
  /**
   * Path prefix Caddy matches on inbound requests. Leading slash
   * required; no trailing slash. Example: "/media".
   */
  readonly path: string
  /**
   * R2 bucket name the path forwards to on the local SeaweedFS
   * sidecar. Caddy rewrites the request to `/<bucketName>/<rest>`
   * and reverse-proxies to 127.0.0.1:8333.
   */
  readonly bucketName: string
  /**
   * Override the sidecar address. Default `127.0.0.1:8333` — the
   * S3 endpoint groundflare-r2.service listens on.
   */
  readonly upstream?: string
}

export interface CaddySite {
  /** Hostname that terminates here. e.g. "api.example.com". Required. */
  readonly hostname: string

  /** Upstream `host:port` that Caddy reverse-proxies to. */
  readonly upstream: string

  /**
   * Absolute path on the VPS to a directory of static files. When set,
   * Caddy serves matching files directly (fast, no Worker invocation)
   * and falls through to the upstream reverse_proxy for everything else.
   * Matches wrangler's `[assets].directory` semantics.
   */
  readonly assetsPath?: string

  /**
   * Public path routes to the local SeaweedFS sidecar. When an R2
   * binding declares `groundflare.public_path = "/media"` in its
   * wrangler config, requests under that path get forwarded to the
   * sidecar instead of the Worker — this is how emdash and similar
   * CMSes serve user-uploaded media from a self-host box without
   * signed-URL detours through the Worker.
   */
  readonly r2PublicRoutes?: readonly CaddyR2PublicRoute[]

  /**
   * Enable gzip/zstd response compression. Default true — the workerd
   * router doesn't compress, and most tenant Workers don't either.
   */
  readonly encode?: boolean

  /** Extra Caddyfile directives inside the site block (raw text). */
  readonly extra?: readonly string[]
}

export interface CaddyfileOptions {
  /** ACME contact email for Let's Encrypt. Required for automatic TLS. */
  readonly email: string

  readonly sites: readonly CaddySite[]

  /**
   * Override the ACME CA. Default = Let's Encrypt production.
   * Use the staging URL during early bootstrap to avoid rate limits.
   */
  readonly acmeCa?: string

  /**
   * Default admin API address. Caddy binds to localhost:2019 by default;
   * set to null to disable entirely.
   */
  readonly adminAddress?: string | null

  /**
   * Controls Caddy's `persist_config` global option. Default true (which
   * is Caddy's own default — the active config is saved to the OS storage
   * dir for resume). Set to false to emit `persist_config off`. Caddy's
   * Caddyfile adapter accepts `off` only; there is no `persist_config on`
   * keyword, so we emit nothing when the behaviour is on.
   */
  readonly persistConfig?: boolean
}

const GENERATED_HEADER =
  '# GENERATED by groundflare — do not edit by hand.\n' +
  '# Regenerated on every `groundflare deploy`; local edits will be lost.\n\n'

export function generateCaddyfile(opts: CaddyfileOptions): string {
  if (!isValidEmail(opts.email)) {
    throw new TypeError(`Caddyfile: invalid email address: ${opts.email}`)
  }

  for (const site of opts.sites) {
    if (!isValidHostname(site.hostname)) {
      throw new TypeError(`Caddyfile: invalid hostname: ${site.hostname}`)
    }
    if (!isValidUpstream(site.upstream)) {
      throw new TypeError(`Caddyfile: invalid upstream: ${site.upstream}`)
    }
  }

  const globalLines: string[] = [`email ${opts.email}`]
  if (opts.acmeCa !== undefined) globalLines.push(`acme_ca ${opts.acmeCa}`)
  if (opts.adminAddress === null) globalLines.push('admin off')
  else if (opts.adminAddress !== undefined)
    globalLines.push(`admin ${opts.adminAddress}`)
  if (opts.persistConfig === false) globalLines.push('persist_config off')

  const siteBlocks = opts.sites.map(renderSite).join('\n\n')

  return (
    GENERATED_HEADER +
    '{\n' +
    globalLines.map((l) => `  ${l}`).join('\n') +
    '\n}\n' +
    (siteBlocks ? '\n' + siteBlocks + '\n' : '')
  )
}

function renderSite(site: CaddySite): string {
  const lines: string[] = []
  const publicRoutes = site.r2PublicRoutes ?? []
  for (const r of publicRoutes) validatePublicRoute(r)

  // R2 public routes come BEFORE the static/worker routing so their
  // prefix matches terminate early (Caddy evaluates handle blocks in
  // declaration order for the same request).
  //
  // Pattern:
  //   GET /media/photos/cat.jpg
  //   ↓ handle_path strips /media → inner {uri} == /photos/cat.jpg
  //   ↓ rewrite prepends /<bucket> → /<bucket>/photos/cat.jpg
  //   ↓ reverse_proxy → weed serves /{bucket}/photos/cat.jpg
  for (const route of publicRoutes) {
    const upstream = route.upstream ?? '127.0.0.1:8333'
    lines.push(`handle_path ${route.path}/* {`)
    lines.push(`  rewrite * /${route.bucketName}{uri}`)
    lines.push(`  reverse_proxy ${upstream}`)
    lines.push('}')
    lines.push('')
  }

  if (site.assetsPath !== undefined) {
    // Static assets: Caddy serves files from disk first; requests that
    // don't match a file fall through to the Worker via reverse_proxy.
    lines.push(`root * ${site.assetsPath}`)
    lines.push('')
    lines.push('@static file')
    lines.push('handle @static {')
    lines.push('  file_server')
    lines.push('}')
    lines.push('')
    lines.push('handle {')
    lines.push(`  reverse_proxy ${site.upstream}`)
    lines.push('}')
  } else {
    lines.push(`reverse_proxy ${site.upstream}`)
  }

  if (site.encode !== false) lines.push('encode gzip zstd')
  lines.push('log {')
  lines.push('  output stdout')
  lines.push('  format json')
  lines.push('}')
  if (site.extra && site.extra.length > 0) lines.push(...site.extra)

  return (
    `${site.hostname} {\n` +
    lines.map((l) => `  ${l}`).join('\n') +
    '\n}'
  )
}

function validatePublicRoute(route: CaddyR2PublicRoute): void {
  if (!route.path.startsWith('/') || route.path === '/') {
    throw new TypeError(
      `Caddyfile: r2PublicRoute.path must start with a single slash and be non-empty; got ${JSON.stringify(route.path)}`,
    )
  }
  if (route.path.endsWith('/')) {
    throw new TypeError(
      `Caddyfile: r2PublicRoute.path must not end with a trailing slash; got ${JSON.stringify(route.path)}`,
    )
  }
  if (!/^[A-Za-z0-9._-]+$/.test(route.bucketName)) {
    throw new TypeError(
      `Caddyfile: r2PublicRoute.bucketName contains invalid characters; got ${JSON.stringify(route.bucketName)}`,
    )
  }
  if (route.upstream !== undefined && !isValidUpstream(route.upstream)) {
    throw new TypeError(
      `Caddyfile: r2PublicRoute.upstream invalid; got ${JSON.stringify(route.upstream)}`,
    )
  }
}

// ─── Validation ────────────────────────────────────────────────────

function isValidEmail(value: string): boolean {
  // Minimal validation: exactly one @, non-empty on both sides, at least
  // one dot in the domain. We don't attempt RFC 5322 — ACME registration
  // will reject garbage more definitively.
  const at = value.indexOf('@')
  if (at <= 0 || at === value.length - 1) return false
  if (value.indexOf('@', at + 1) !== -1) return false
  const domain = value.slice(at + 1)
  return domain.includes('.') && !domain.startsWith('.') && !domain.endsWith('.')
}

const HOSTNAME_LABEL_RE = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/i

function isValidHostname(value: string): boolean {
  if (value.length === 0 || value.length > 253) return false
  const labels = value.split('.')
  return labels.every((label) => HOSTNAME_LABEL_RE.test(label))
}

const UPSTREAM_RE = /^[a-z0-9._:/-]+(?::\d+)?$/i

function isValidUpstream(value: string): boolean {
  return value.length > 0 && UPSTREAM_RE.test(value)
}
