import { describe, it, expect } from 'vitest'
import { generateBunShim } from '../../../../src/runtime/bun/shim.js'

describe('generateBunShim', () => {
  it('rejects empty entryModule', () => {
    expect(() => generateBunShim({ entryModule: '' })).toThrow('entryModule')
  })

  it('rejects listenAddress without a port', () => {
    expect(() =>
      generateBunShim({ entryModule: './user.js', listenAddress: '0.0.0.0' }),
    ).toThrow(/port/)
  })

  it('rejects invalid port values', () => {
    expect(() =>
      generateBunShim({ entryModule: './user.js', listenAddress: '0.0.0.0:0' }),
    ).toThrow(/port/)
    expect(() =>
      generateBunShim({
        entryModule: './user.js',
        listenAddress: '0.0.0.0:70000',
      }),
    ).toThrow(/port/)
    expect(() =>
      generateBunShim({
        entryModule: './user.js',
        listenAddress: 'localhost:abc',
      }),
    ).toThrow(/port/)
  })

  it('includes the GENERATED-by provenance header', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    expect(src.startsWith('// GENERATED by groundflare')).toBe(true)
    expect(src).toContain('Regenerated on every `groundflare deploy`')
  })

  it('imports the user entry via the provided specifier', () => {
    const src = generateBunShim({ entryModule: './workers/api/user.js' })
    expect(src).toContain('import user from "./workers/api/user.js"')
  })

  it('defaults listen to 0.0.0.0:8080', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    expect(src).toContain('hostname: "0.0.0.0"')
    expect(src).toContain('port: 8080')
  })

  it('splits custom listenAddress into hostname + port', () => {
    const src = generateBunShim({
      entryModule: './user.js',
      listenAddress: '127.0.0.1:3001',
    })
    expect(src).toContain('hostname: "127.0.0.1"')
    expect(src).toContain('port: 3001')
  })

  it('embeds vars as a JSON literal at build time', () => {
    const src = generateBunShim({
      entryModule: './user.js',
      vars: { APP_NAME: 'demo', FEATURE_FLAGS: 'a,b', COUNT: 42, ON: true },
    })
    expect(src).toContain(
      'const VARS = {"APP_NAME":"demo","FEATURE_FLAGS":"a,b","COUNT":42,"ON":true}',
    )
  })

  it('uses an empty VARS object when no vars supplied', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    expect(src).toContain('const VARS = {}')
  })

  it('serialises KV bindings with shard counts alphabetically', () => {
    const src = generateBunShim({
      entryModule: './user.js',
      kvNamespaces: [{ binding: 'Z_CACHE' }, { binding: 'A_CACHE', shards: 4 }],
    })
    expect(src).toContain(
      'const KV_BINDINGS = {"A_CACHE":{"shards":4},"Z_CACHE":{"shards":1}}',
    )
  })

  it('serialises D1 bindings with database names', () => {
    const src = generateBunShim({
      entryModule: './user.js',
      d1Databases: [{ binding: 'DB', databaseName: 'prod' }],
    })
    expect(src).toContain(
      'const D1_BINDINGS = {"DB":{"databaseName":"prod"}}',
    )
  })

  it('serialises R2 bindings with bucketName fallback to binding name', () => {
    const src = generateBunShim({
      entryModule: './user.js',
      r2Buckets: [
        { binding: 'ASSETS', bucketName: 'my-assets' },
        { binding: 'UPLOADS' }, // no explicit bucket
      ],
    })
    expect(src).toContain(
      'const R2_BINDINGS = {"ASSETS":{"bucketName":"my-assets"},"UPLOADS":{"bucketName":"UPLOADS"}}',
    )
  })

  it('wires KV facade to the real BunKVAdapter (Phase 2b+)', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    // Imports the adapter from the file shipped alongside server.ts
    expect(src).toContain('import { BunKVAdapter } from "./adapters/kv.ts"')
    // makeKvFacade opens a per-binding SQLite file rooted in stateBaseDir
    expect(src).toContain(
      'return BunKVAdapter.open(`${STATE_BASE_DIR}/kv/${binding}.sqlite`)',
    )
    // No more Phase 1 stub error for KV — D1 and R2 still throw until
    // Phase 2c/2d wires them.
    expect(src).not.toContain(
      'KV.${op}() — groundflare Bun adapter not yet implemented',
    )
  })

  it('wires D1 facade to the real BunD1Adapter (Phase 2c+)', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    expect(src).toContain('import { BunD1Adapter } from "./adapters/d1.ts"')
    expect(src).toContain(
      'return BunD1Adapter.open(`${STATE_BASE_DIR}/d1/${databaseName}.sqlite`)',
    )
    expect(src).not.toContain(
      'D1.${op}() — groundflare Bun adapter not yet implemented',
    )
  })

  it('R2 stub still throws a Phase-2 message (2d not yet landed)', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    expect(src).toContain(
      'R2.${op}() — groundflare Bun adapter not yet implemented (Phase 2)',
    )
  })

  // D1 stub assertions removed — Phase 2c replaced the stub with
  // BunD1Adapter.open() which already exposes the full CF D1 surface
  // via its own class.

  it('bakes stateBaseDir into the shim (default /var/lib/groundflare)', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    expect(src).toContain('const STATE_BASE_DIR = "/var/lib/groundflare"')
  })

  it('honours a custom stateBaseDir', () => {
    const src = generateBunShim({
      entryModule: './user.js',
      stateBaseDir: '/srv/groundflare',
    })
    expect(src).toContain('const STATE_BASE_DIR = "/srv/groundflare"')
  })

  it('exposes CF R2 object + multipart methods in the stub', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    for (const m of [
      'get:',
      'head:',
      'put:',
      'delete:',
      'list:',
      'createMultipartUpload:',
      'resumeMultipartUpload:',
    ]) {
      expect(src).toContain(m)
    }
  })

  it('dispatches the fetch event into user.fetch with env + ctx', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    expect(src).toMatch(/return user\.fetch\(request, ENV, ctx\)/)
  })

  it('ctx.waitUntil swallows rejections rather than crashing the process', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    expect(src).toContain(
      'waitUntil(promise) { promise.catch((err) => console.error("waitUntil:", err)) }',
    )
  })

  it('installs SIGTERM/SIGINT handlers that drain before exit', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    expect(src).toContain('"SIGTERM", "SIGINT"')
    expect(src).toContain('await server.stop(false)')
  })

  it('emits a startup log line so journald shows clear boot confirmation', () => {
    const src = generateBunShim({ entryModule: './user.js' })
    expect(src).toContain(
      'groundflare Bun runtime listening on ${server.hostname}:${server.port}',
    )
  })

  it('is deterministic — same input produces byte-identical output', () => {
    const opts = {
      entryModule: './user.js',
      vars: { A: '1', B: '2' },
      kvNamespaces: [{ binding: 'CACHE', shards: 4 }, { binding: 'OTHER' }],
      d1Databases: [{ binding: 'DB', databaseName: 'prod' }],
      r2Buckets: [{ binding: 'ASSETS', bucketName: 'x' }],
    }
    const a = generateBunShim(opts)
    const b = generateBunShim(opts)
    expect(a).toBe(b)
  })

  it('binding ordering is normalised so manifest reorderings do not churn the diff', () => {
    const a = generateBunShim({
      entryModule: './user.js',
      kvNamespaces: [{ binding: 'B' }, { binding: 'A' }],
    })
    const b = generateBunShim({
      entryModule: './user.js',
      kvNamespaces: [{ binding: 'A' }, { binding: 'B' }],
    })
    expect(a).toBe(b)
  })
})
