import { describe, it, expect } from 'vitest'
import { generateBunSystemdUnit } from '../../../../src/runtime/bun/systemd.js'

describe('generateBunSystemdUnit', () => {
  const base = { entryPath: '/var/lib/groundflare/server.js' }

  it('throws when entryPath is missing', () => {
    expect(() => generateBunSystemdUnit({ entryPath: '' })).toThrow('entryPath')
  })

  it('emits the GENERATED-by header so humans know not to hand-edit', () => {
    const unit = generateBunSystemdUnit(base)
    expect(unit.startsWith('# GENERATED by groundflare')).toBe(true)
  })

  it('has [Unit], [Service], [Install] sections in the systemd-required order', () => {
    const unit = generateBunSystemdUnit(base)
    const unitIdx = unit.indexOf('[Unit]')
    const serviceIdx = unit.indexOf('[Service]')
    const installIdx = unit.indexOf('[Install]')
    expect(unitIdx).toBeGreaterThan(0)
    expect(serviceIdx).toBeGreaterThan(unitIdx)
    expect(installIdx).toBeGreaterThan(serviceIdx)
  })

  it('wires ExecStart to bun run <entryPath> with default binary path', () => {
    const unit = generateBunSystemdUnit(base)
    expect(unit).toContain(
      'ExecStart=/usr/local/bin/bun run /var/lib/groundflare/server.js',
    )
  })

  it('respects custom bunBinary', () => {
    const unit = generateBunSystemdUnit({
      ...base,
      bunBinary: '/opt/bun/bin/bun',
    })
    expect(unit).toContain('ExecStart=/opt/bun/bin/bun run')
  })

  it('uses default environment file with - prefix so missing file is not fatal', () => {
    const unit = generateBunSystemdUnit(base)
    expect(unit).toContain('EnvironmentFile=-/etc/groundflare/environment')
  })

  it('omits EnvironmentFile when environmentFile is null', () => {
    const unit = generateBunSystemdUnit({ ...base, environmentFile: null })
    expect(unit).not.toContain('EnvironmentFile=')
  })

  it('accepts custom environmentFile path', () => {
    const unit = generateBunSystemdUnit({
      ...base,
      environmentFile: '/etc/myapp/env',
    })
    expect(unit).toContain('EnvironmentFile=-/etc/myapp/env')
  })

  it('defaults user/group to groundflare', () => {
    const unit = generateBunSystemdUnit(base)
    expect(unit).toContain('User=groundflare')
    expect(unit).toContain('Group=groundflare')
  })

  it('allows overriding user and group', () => {
    const unit = generateBunSystemdUnit({
      ...base,
      user: 'app',
      group: 'app',
    })
    expect(unit).toContain('User=app')
    expect(unit).toContain('Group=app')
    expect(unit).not.toContain('User=groundflare')
  })

  it('emits the default resource limits', () => {
    const unit = generateBunSystemdUnit(base)
    expect(unit).toContain('LimitNOFILE=65536')
    expect(unit).toContain('MemoryMax=80%')
    expect(unit).toContain('CPUQuota=80%')
    expect(unit).toContain('TasksMax=1024')
  })

  it('respects custom resource limits', () => {
    const unit = generateBunSystemdUnit({
      ...base,
      memoryMaxPercent: 50,
      cpuQuotaPercent: 75,
      limitNoFile: 131072,
      tasksMax: 4096,
    })
    expect(unit).toContain('LimitNOFILE=131072')
    expect(unit).toContain('MemoryMax=50%')
    expect(unit).toContain('CPUQuota=75%')
    expect(unit).toContain('TasksMax=4096')
  })

  it('rejects memoryMaxPercent outside (0, 100]', () => {
    expect(() =>
      generateBunSystemdUnit({ ...base, memoryMaxPercent: 0 }),
    ).toThrow('memoryMaxPercent')
    expect(() =>
      generateBunSystemdUnit({ ...base, memoryMaxPercent: 101 }),
    ).toThrow('memoryMaxPercent')
    expect(() =>
      generateBunSystemdUnit({ ...base, memoryMaxPercent: NaN }),
    ).toThrow('memoryMaxPercent')
  })

  it('rejects cpuQuotaPercent outside (0, 100]', () => {
    expect(() =>
      generateBunSystemdUnit({ ...base, cpuQuotaPercent: -1 }),
    ).toThrow('cpuQuotaPercent')
    expect(() =>
      generateBunSystemdUnit({ ...base, cpuQuotaPercent: 200 }),
    ).toThrow('cpuQuotaPercent')
  })

  it('uses Restart=on-failure with 5 second delay by default', () => {
    const unit = generateBunSystemdUnit(base)
    expect(unit).toContain('Restart=on-failure')
    expect(unit).toContain('RestartSec=5')
  })

  it('allows Restart=always for hot-reload-friendly scenarios', () => {
    const unit = generateBunSystemdUnit({ ...base, restart: 'always' })
    expect(unit).toContain('Restart=always')
  })

  it('captures stdout/stderr to journald with identifier', () => {
    const unit = generateBunSystemdUnit(base)
    expect(unit).toContain('StandardOutput=journal')
    expect(unit).toContain('StandardError=journal')
    expect(unit).toContain('SyslogIdentifier=groundflare-worker')
  })

  it('appends extraServiceLines verbatim before closing [Install]', () => {
    const unit = generateBunSystemdUnit({
      ...base,
      extraServiceLines: [
        'NoNewPrivileges=yes',
        'ProtectSystem=strict',
      ],
    })
    expect(unit).toContain('NoNewPrivileges=yes')
    expect(unit).toContain('ProtectSystem=strict')
    // extras are in Service, not Install
    const extrasIdx = unit.indexOf('NoNewPrivileges=yes')
    const installIdx = unit.indexOf('[Install]')
    expect(extrasIdx).toBeLessThan(installIdx)
  })

  it('defaults WantedBy to multi-user.target', () => {
    const unit = generateBunSystemdUnit(base)
    expect(unit).toContain('WantedBy=multi-user.target')
  })

  it('accepts a custom Description', () => {
    const unit = generateBunSystemdUnit({
      ...base,
      description: 'groundflare Bun runtime for example-workspace',
    })
    expect(unit).toContain(
      'Description=groundflare Bun runtime for example-workspace',
    )
  })
})
