name = "hello"
main = "src/index.js"
compatibility_date = "2026-04-01"

[vars]
GREETING = "hello from groundflare"

[[kv_namespaces]]
binding = "CACHE"
id = "fake-id-for-poc"

[[d1_databases]]
binding = "DB"
database_name = "hello"
database_id = "fake-d1-id-for-poc"
