/**
 * Router Worker generator.
 *
 * groundflare generates the Router Worker at every deploy — it's not
 * user code. The Router sits at the single workerd socket and dispatches
 * requests to tenant Workers by Host header (via service bindings).
 *
 * Keeps the body small and exhaustively tested because a bug here takes
 * down the entire workspace. Edge cases covered in the body + unit tests:
 *   - Missing or malformed Host
 *   - Host with port (strip)
 *   - Uppercase Host (lowercase normalization)
 *   - Target Worker missing (should not happen at runtime, but defensive)
 *   - Cron dispatch via `event.cron = "<worker>|<expression>"`
 *
 * Per design/workspaces.md: not user-extensible in v0.2. Regenerated on
 * every `groundflare deploy` from the workspace manifest.
 */

import type { WorkspaceWorker } from './types.js'

/**
 * Map a worker name to the env binding the router sees it as.
 * Example: "api-gateway" → "WORKER_API_GATEWAY"
 */
export function routerBindingName(workerName: string): string {
  return 'WORKER_' + workerName.toUpperCase().replace(/-/g, '_')
}

export interface RouterGenerationInfo {
  /** Workers with a domain — included in the Host→binding map. */
  readonly routableWorkers: readonly WorkspaceWorker[]
  /** Every worker, for scheduled() cron dispatch (whether or not they're routable). */
  readonly allWorkers: readonly WorkspaceWorker[]
}

export function collectRouterInfo(workers: readonly WorkspaceWorker[]): RouterGenerationInfo {
  return {
    routableWorkers: workers.filter((w) => w.domain !== undefined),
    allWorkers: workers,
  }
}

/**
 * Produce the Router Worker's ES module source text. The JS is written
 * verbatim into the capnp output as an inline `esModule`, so the code is
 * dependency-free and expects nothing outside V8 + workerd's standard APIs.
 */
export function generateRouterJs(workers: readonly WorkspaceWorker[]): string {
  const info = collectRouterInfo(workers)

  const routeLines = info.routableWorkers.map((w) => {
    const host = JSON.stringify(w.domain!.toLowerCase())
    const binding = JSON.stringify(routerBindingName(w.name))
    return `  ${host}: ${binding},`
  })

  const cronBindings = info.allWorkers.map((w) => {
    return `  ${JSON.stringify(w.name)}: ${JSON.stringify(routerBindingName(w.name))},`
  })

  return `// GENERATED by groundflare — do not edit by hand.
// Router dispatches tenant traffic by Host header; regenerated on every
// \`groundflare deploy\`. See design/workspaces.md#router-worker.

const ROUTES = {
${routeLines.join('\n')}
}

const CRON_BINDINGS = {
${cronBindings.join('\n')}
}

function plain(body, status) {
  return new Response(body, {
    status,
    headers: { 'content-type': 'text/plain; charset=utf-8' },
  })
}

async function dispatchScheduled(url, env, ctx) {
  if (url.hostname !== '127.0.0.1' && url.hostname !== 'localhost') {
    return plain('not found', 404)
  }
  const workerName = url.searchParams.get('worker')
  if (!workerName) return plain('missing worker parameter', 400)
  const bindingName = CRON_BINDINGS[workerName]
  if (!bindingName) return plain('unknown worker: ' + workerName, 404)
  const target = env[bindingName]
  if (!target || typeof target.scheduled !== 'function') {
    return plain('target has no scheduled handler', 404)
  }
  const cron = url.searchParams.get('cron') || ''
  await target.scheduled(
    { cron, scheduledTime: Date.now(), type: 'scheduled' },
    env,
    ctx,
  )
  return plain('ok', 200)
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)

    // Internal cron dispatch: systemd .timer units curl POST this path.
    // Gated on hostname = 127.0.0.1/localhost; external requests for the
    // same path get a plain 404 (no information leak about the feature).
    if (url.pathname === '/__scheduled') {
      if (request.method !== 'POST') {
        return new Response('method not allowed', {
          status: 405,
          headers: { allow: 'POST', 'content-type': 'text/plain; charset=utf-8' },
        })
      }
      return dispatchScheduled(url, env, ctx)
    }

    // Normal host-based dispatch to tenant Workers.
    const hostname = url.hostname.toLowerCase()
    const bindingName = ROUTES[hostname]
    if (!bindingName) {
      return plain('groundflare: no Worker matches host ' + hostname, 404)
    }
    const target = env[bindingName]
    if (!target) {
      return plain('groundflare: target binding missing for ' + bindingName, 503)
    }
    return target.fetch(request)
  },
}
`
}
