/**
 * Router Worker generator.
 *
 * groundflare generates the Router Worker at every deploy — it's not
 * user code. The Router sits at the single workerd socket and dispatches
 * requests to tenant Workers by Host header (via service bindings).
 *
 * Keeps the body small and exhaustively tested because a bug here takes
 * down the entire workspace. Edge cases covered in the body + unit tests:
 *   - Missing or malformed Host
 *   - Host with port (strip)
 *   - Uppercase Host (lowercase normalization)
 *   - Target Worker missing (should not happen at runtime, but defensive)
 *   - Cron dispatch via `event.cron = "<worker>|<expression>"`
 *
 * Per design/workspaces.md: not user-extensible in v0.2. Regenerated on
 * every `groundflare deploy` from the workspace manifest.
 */

import type { WorkspaceWorker } from './types.js'

/**
 * Map a worker name to the env binding the router sees it as.
 * Example: "api-gateway" → "WORKER_API_GATEWAY"
 */
export function routerBindingName(workerName: string): string {
  return 'WORKER_' + workerName.toUpperCase().replace(/-/g, '_')
}

export interface RouterGenerationInfo {
  /** Workers with a domain — included in the Host→binding map. */
  readonly routableWorkers: readonly WorkspaceWorker[]
  /** Every worker, for scheduled() cron dispatch (whether or not they're routable). */
  readonly allWorkers: readonly WorkspaceWorker[]
}

export function collectRouterInfo(workers: readonly WorkspaceWorker[]): RouterGenerationInfo {
  return {
    routableWorkers: workers.filter((w) => w.domain !== undefined),
    allWorkers: workers,
  }
}

/**
 * Produce the Router Worker's ES module source text. The JS is written
 * verbatim into the capnp output as an inline `esModule`, so the code is
 * dependency-free and expects nothing outside V8 + workerd's standard APIs.
 */
export function generateRouterJs(workers: readonly WorkspaceWorker[]): string {
  const info = collectRouterInfo(workers)

  const routeLines = info.routableWorkers.map((w) => {
    const host = JSON.stringify(w.domain!.toLowerCase())
    const binding = JSON.stringify(routerBindingName(w.name))
    return `  ${host}: ${binding},`
  })

  const cronBindings = info.allWorkers.map((w) => {
    return `  ${JSON.stringify(w.name)}: ${JSON.stringify(routerBindingName(w.name))},`
  })

  return `// GENERATED by groundflare — do not edit by hand.
// Router dispatches tenant traffic by Host header; regenerated on every
// \`groundflare deploy\`. See design/workspaces.md#router-worker.

const ROUTES = {
${routeLines.join('\n')}
}

const CRON_BINDINGS = {
${cronBindings.join('\n')}
}

export default {
  async fetch(request, env, ctx) {
    const hostname = new URL(request.url).hostname.toLowerCase()
    const bindingName = ROUTES[hostname]
    if (!bindingName) {
      return new Response('groundflare: no Worker matches host ' + hostname, {
        status: 404,
        headers: { 'content-type': 'text/plain; charset=utf-8' },
      })
    }
    const target = env[bindingName]
    if (!target) {
      return new Response('groundflare: target binding missing for ' + bindingName, {
        status: 503,
        headers: { 'content-type': 'text/plain; charset=utf-8' },
      })
    }
    return target.fetch(request)
  },

  async scheduled(event, env, ctx) {
    // Cron triggers reach the router via systemd timers that post to
    // __scheduled with \`event.cron = "<worker>|<expression>"\`.
    const raw = typeof event.cron === 'string' ? event.cron : ''
    const sep = raw.indexOf('|')
    if (sep < 1) return
    const workerName = raw.slice(0, sep)
    const cron = raw.slice(sep + 1)
    const bindingName = CRON_BINDINGS[workerName]
    if (!bindingName) return
    const target = env[bindingName]
    if (!target || typeof target.scheduled !== 'function') return
    await target.scheduled({ ...event, cron }, env, ctx)
  },
}
`
}
