name = "hono-api"
main = "src/index.ts"
compatibility_date = "2026-04-01"

[vars]
APP_NAME = "groundflare-hono-demo"

[[kv_namespaces]]
binding = "CACHE"
id = "fake-id-for-local-dev"

[[d1_databases]]
binding = "DB"
database_name = "notes"
database_id = "fake-d1-id-for-local-dev"

[groundflare]
domain = "hono-api.example.com"
