/**
 * Source text for the D1 adapter Worker that runs inside workerd.
 *
 * Unlike KV (which uses workerd's KV-style state.storage), D1 needs SQL
 * semantics. We use workerd's SqlStorage (`ctx.storage.sql`), which is
 * available only when the DO namespace is configured with both
 * `enableSql = true` AND `localDisk` storage (NOT `inMemory`). The
 * `inMemory` storage path uses a non-SQL ActorCache implementation;
 * this is undocumented but verified empirically and matches workerd
 * source intent.
 *
 * RPC API mirrors the Node-side SqliteD1Adapter so test conformance
 * stays in lock-step. The tenant shim (generateTenantD1Shim) translates
 * `env.DB.prepare(sql).bind(args).run()` into a single RPC call.
 */

import { TENANT_METRICS_SHIM_SOURCE } from '../metrics/tenant-shim-source.js'

export const D1_ADAPTER_DO_SOURCE = String.raw`// GENERATED by groundflare.
// D1 adapter Durable Object. Backs one tenant-database pair with
// workerd's SqlStorage (state.storage.sql).

import { DurableObject } from 'cloudflare:workers'

const SERVED_BY = 'groundflare-workerd'

export class D1Store extends DurableObject {
  // ─── single-statement entry points ─────────────────────────────

  async d1Run(sql, args) {
    const start = Date.now()
    let lastRowId = 0
    let changes = 0
    try {
      const cursor = this.ctx.storage.sql.exec(sql, ...(args ?? []))
      // Drain so rowsWritten populates.
      for (const _ of cursor) { /* discard */ }
      changes = cursor.rowsWritten ?? 0
      // SQLite's last_insert_rowid is per-connection; SqlStorage reuses
      // one connection so this is safe to query right after a write.
      const tail = [...this.ctx.storage.sql.exec('SELECT last_insert_rowid() AS rowid')]
      lastRowId = Number(tail[0]?.rowid ?? 0)
    } catch (err) {
      return d1Error(err, Date.now() - start)
    }
    return {
      results: [],
      success: true,
      meta: {
        duration: Date.now() - start,
        last_row_id: lastRowId,
        changes,
        served_by: SERVED_BY,
        rows_read: 0,
        rows_written: changes,
      },
    }
  }

  async d1All(sql, args) {
    const start = Date.now()
    try {
      const cursor = this.ctx.storage.sql.exec(sql, ...(args ?? []))
      const results = cursor.toArray()
      return {
        results,
        success: true,
        meta: {
          duration: Date.now() - start,
          last_row_id: 0,
          changes: 0,
          served_by: SERVED_BY,
          rows_read: cursor.rowsRead ?? results.length,
          rows_written: 0,
        },
      }
    } catch (err) {
      return d1Error(err, Date.now() - start)
    }
  }

  async d1First(sql, args, column) {
    const cursor = this.ctx.storage.sql.exec(sql, ...(args ?? []))
    const it = cursor[Symbol.iterator]()
    const first = it.next()
    if (first.done) return null
    if (column !== undefined) {
      const v = first.value[column]
      return v === undefined ? null : v
    }
    return first.value
  }

  async d1Raw(sql, args) {
    const cursor = this.ctx.storage.sql.exec(sql, ...(args ?? []))
    return cursor.raw().toArray()
  }

  // ─── batch / exec ───────────────────────────────────────────────

  async d1Batch(statements) {
    if (statements.length === 0) return []
    const results = []
    try {
      this.ctx.storage.transactionSync(() => {
        for (const stmt of statements) {
          const sql = stmt.sql
          const args = stmt.args ?? []
          const trimmed = sql.trimStart().slice(0, 6).toUpperCase()
          const useAll =
            trimmed.startsWith('SELECT') ||
            trimmed.startsWith('WITH ') ||
            trimmed.startsWith('PRAGMA') ||
            /\bRETURNING\b/i.test(sql)
          const start = Date.now()
          const cursor = this.ctx.storage.sql.exec(sql, ...args)
          if (useAll) {
            const rows = cursor.toArray()
            results.push({
              results: rows,
              success: true,
              meta: {
                duration: Date.now() - start,
                last_row_id: 0,
                changes: 0,
                served_by: SERVED_BY,
                rows_read: cursor.rowsRead ?? rows.length,
                rows_written: 0,
              },
            })
          } else {
            for (const _ of cursor) { /* drain */ }
            const tail = [...this.ctx.storage.sql.exec('SELECT last_insert_rowid() AS rowid')]
            results.push({
              results: [],
              success: true,
              meta: {
                duration: Date.now() - start,
                last_row_id: Number(tail[0]?.rowid ?? 0),
                changes: cursor.rowsWritten ?? 0,
                served_by: SERVED_BY,
                rows_read: 0,
                rows_written: cursor.rowsWritten ?? 0,
              },
            })
          }
        }
      })
    } catch (err) {
      throw new Error('D1.batch failed: ' + (err && err.message ? err.message : String(err)))
    }
    return results
  }

  async d1Exec(sql) {
    const start = Date.now()
    // SqlStorage exec() takes one statement at a time. Split on naive ';'
    // boundaries — fine for migrations with simple statements; users
    // who need to embed semicolons inside string literals should use
    // .prepare() + parameter binding instead.
    let count = 0
    for (const segment of sql.split(';')) {
      const trimmed = segment.trim()
      if (trimmed.length === 0) continue
      const cursor = this.ctx.storage.sql.exec(trimmed)
      for (const _ of cursor) { /* drain */ }
      count++
    }
    return { count, duration: Date.now() - start }
  }
}

function d1Error(err, duration) {
  const message = err && err.message ? err.message : String(err)
  return {
    results: [],
    success: false,
    error: message,
    meta: {
      duration,
      last_row_id: 0,
      changes: 0,
      served_by: SERVED_BY,
      rows_read: 0,
      rows_written: 0,
    },
  }
}

export default {
  async fetch() {
    return new Response('groundflare D1 adapter — DO access only', { status: 404 })
  },
}
`

/**
 * Generate the tenant shim module source for a worker with D1 bindings.
 *
 * The shim wraps each `env.DB` (a DO namespace binding) into an object
 * matching the CF D1 API: prepare()/batch()/exec() at the top level,
 * and PreparedStatement bind/first/run/all/raw on the result of prepare().
 */
export interface GenerateTenantD1ShimOptions {
  /** See GenerateTenantKvShimOptions.workerName. */
  readonly workerName: string
}

export function generateTenantD1Shim(
  d1BindingNames: readonly string[],
  opts: GenerateTenantD1ShimOptions,
): string {
  const listLiteral = JSON.stringify([...d1BindingNames].sort())
  return String.raw`// GENERATED by groundflare — tenant D1 shim.
// Wraps DO-backed D1 adapter as the CF D1 API.

import user from './user.js'
// Re-export user's named exports so workerd can resolve DO classes
// declared on the user module.
export * from './user.js'

const GF_WORKER_NAME = ${JSON.stringify(opts.workerName)}
${TENANT_METRICS_SHIM_SOURCE}
const D1_BINDINGS = new Set(${listLiteral})

function makePreparedStatement(binding, stub, sql, args) {
  return {
    bind(...newArgs) {
      return makePreparedStatement(binding, stub, sql, [...args, ...newArgs])
    },
    async first(column) {
      return gf_timeD1(binding, 'first', () => stub.d1First(sql, args, column))
    },
    async run() {
      return gf_timeD1(binding, 'run', () => stub.d1Run(sql, args))
    },
    async all() {
      return gf_timeD1(binding, 'all', () => stub.d1All(sql, args))
    },
    async raw() {
      return gf_timeD1(binding, 'raw', () => stub.d1Raw(sql, args))
    },
    // Internal accessor used by batch() to extract { sql, args } pairs.
    _gfStatement: { sql, args },
  }
}

function makeFacade(doNamespace, binding) {
  const stub = () => doNamespace.get(doNamespace.idFromName('default'))
  return {
    prepare(sql) {
      return makePreparedStatement(binding, stub(), sql, [])
    },
    async batch(statements) {
      return gf_timeD1(binding, 'batch', () => {
        const payload = statements.map((s) => {
          const inner = s._gfStatement
          if (!inner) {
            throw new TypeError('D1.batch: every entry must be the result of .prepare()')
          }
          return inner
        })
        return stub().d1Batch(payload)
      })
    },
    async exec(sql) {
      return gf_timeD1(binding, 'exec', () => stub().d1Exec(sql))
    },
  }
}

function wrapEnv(env) {
  const out = { ...env }
  for (const name of D1_BINDINGS) {
    const raw = out[name]
    if (raw && typeof raw.idFromName === 'function') {
      out[name] = makeFacade(raw, name)
    }
  }
  return out
}

export default {
  async fetch(request, env, ctx) {
    const internal = gf_handleInternalMetrics(request)
    if (internal) return internal
    return user.fetch(request, wrapEnv(env), ctx)
  },
  async scheduled(event, env, ctx) {
    if (user.scheduled) return user.scheduled(event, wrapEnv(env), ctx)
  },
}
`
}

export const D1_DO_CLASS_NAME = 'D1Store'
