import { describe, it, expect } from 'vitest'
import {
  collectRouterInfo,
  generateRouterJs,
  routerBindingName,
} from '../../../../src/runtime/workspace/index.js'
import type { WorkspaceWorker } from '../../../../src/runtime/workspace/index.js'

function worker(
  name: string,
  opts: Partial<WorkspaceWorker> = {},
): WorkspaceWorker {
  return {
    name,
    entryPath: `workers/${name}/code/current/index.js`,
    ...opts,
  }
}

describe('routerBindingName', () => {
  it('uppercases the worker name and prefixes WORKER_', () => {
    expect(routerBindingName('api')).toBe('WORKER_API')
  })

  it('replaces hyphens with underscores', () => {
    expect(routerBindingName('api-gateway')).toBe('WORKER_API_GATEWAY')
  })

  it('works for multi-hyphen names', () => {
    expect(routerBindingName('a-b-c')).toBe('WORKER_A_B_C')
  })
})

describe('collectRouterInfo', () => {
  it('splits workers into routable (with domain) and all', () => {
    const workers = [
      worker('a', { domain: 'a.example.com' }),
      worker('b'),
      worker('c', { domain: 'c.example.com' }),
    ]
    const info = collectRouterInfo(workers)
    expect(info.routableWorkers.map((w) => w.name)).toEqual(['a', 'c'])
    expect(info.allWorkers).toHaveLength(3)
  })

  it('handles empty input', () => {
    const info = collectRouterInfo([])
    expect(info.routableWorkers).toEqual([])
    expect(info.allWorkers).toEqual([])
  })
})

describe('generateRouterJs', () => {
  it('produces a leading "GENERATED" comment so humans see the warning', () => {
    expect(generateRouterJs([])).toMatch(/^\/\/ GENERATED by groundflare/)
  })

  it('declares a ROUTES object mapping domain → binding', () => {
    const js = generateRouterJs([
      worker('api', { domain: 'api.example.com' }),
      worker('admin', { domain: 'admin.example.com' }),
    ])
    expect(js).toContain('"api.example.com": "WORKER_API"')
    expect(js).toContain('"admin.example.com": "WORKER_ADMIN"')
  })

  it('lowercases domains before insertion into ROUTES', () => {
    const js = generateRouterJs([worker('api', { domain: 'API.Example.COM' })])
    expect(js).toContain('"api.example.com": "WORKER_API"')
  })

  it('declares CRON_BINDINGS for every worker (even without a domain)', () => {
    const js = generateRouterJs([
      worker('api', { domain: 'api.example.com' }),
      worker('internal'), // no domain, scheduled via cron only
    ])
    expect(js).toContain('CRON_BINDINGS')
    expect(js).toContain('"internal": "WORKER_INTERNAL"')
  })

  it('exports a default object with fetch and scheduled methods', () => {
    const js = generateRouterJs([worker('x', { domain: 'x.test' })])
    expect(js).toMatch(/export default \{/)
    expect(js).toMatch(/async fetch\(/)
    expect(js).toMatch(/async scheduled\(/)
  })

  it('returns 404 when no host matches', () => {
    const js = generateRouterJs([])
    expect(js).toContain('status: 404')
    expect(js).toContain('no Worker matches host')
  })

  it('returns 503 when ROUTES has a match but the binding is missing', () => {
    // Defensive path — should be impossible in practice, but the router
    // handles it gracefully rather than throwing.
    const js = generateRouterJs([worker('x', { domain: 'x.test' })])
    expect(js).toContain('status: 503')
  })

  it('splits event.cron on | to extract the target worker name', () => {
    const js = generateRouterJs([worker('x', { domain: 'x.test' })])
    expect(js).toContain(`indexOf('|')`)
  })

  it('is deterministic for equivalent inputs', () => {
    const ws = [
      worker('a', { domain: 'a.test' }),
      worker('b', { domain: 'b.test' }),
    ]
    expect(generateRouterJs(ws)).toBe(generateRouterJs(ws))
  })
})

describe('generated router body — executes correctly in V8', () => {
  // Smoke test: actually evaluate the generated JS in a sandbox and invoke
  // its dispatch. If the generator produces invalid JS, this test crashes
  // loudly. We rewrite `export default { ... }` to `return { ... }` so the
  // whole module body (including ROUTES + CRON_BINDINGS consts at top) runs
  // inside a Function and the returned object closes over them.
  function loadRouter(workers: WorkspaceWorker[]): {
    fetch: (req: Request, env: Record<string, unknown>, ctx: unknown) => Promise<Response>
    scheduled: (event: { cron: string }, env: Record<string, unknown>, ctx: unknown) => Promise<void>
  } {
    const source = generateRouterJs(workers)
    const body = source.replace(/export default (\{[\s\S]*\})\s*$/, 'return $1')
    expect(body, 'router source must contain `export default {...}`').not.toBe(source)
    const factory = new Function('Response', 'URL', body)
    return factory(Response, URL) as ReturnType<typeof loadRouter>
  }

  it('dispatches to the correct tenant binding by Host header', async () => {
    const router = loadRouter([worker('api', { domain: 'api.example.com' })])
    let called: string | null = null
    const env = {
      WORKER_API: {
        fetch: async (req: Request): Promise<Response> => {
          called = new URL(req.url).pathname
          return new Response('ok')
        },
      },
    }
    const response = await router.fetch(
      new Request('https://api.example.com/foo'),
      env,
      {},
    )
    expect(response.status).toBe(200)
    expect(called).toBe('/foo')
  })

  it('normalizes request hostname to lowercase', async () => {
    const router = loadRouter([worker('api', { domain: 'api.example.com' })])
    const env = {
      WORKER_API: { fetch: async () => new Response('ok') },
    }
    const response = await router.fetch(
      new Request('https://API.EXAMPLE.COM/'),
      env,
      {},
    )
    expect(response.status).toBe(200)
  })

  it('returns 404 for unknown host', async () => {
    const router = loadRouter([worker('api', { domain: 'api.example.com' })])
    const response = await router.fetch(
      new Request('https://other.example.com/'),
      {},
      {},
    )
    expect(response.status).toBe(404)
    expect(await response.text()).toContain('no Worker matches host')
  })

  it('routes cron triggers to the named worker via CRON_BINDINGS', async () => {
    const router = loadRouter([worker('cleaner')])
    let received: { cron: string; scheduledTime?: number } | null = null
    const env = {
      WORKER_CLEANER: {
        scheduled: async (e: { cron: string; scheduledTime?: number }) => {
          received = e
        },
      },
    }
    await router.scheduled({ cron: 'cleaner|0 */5 * * *' }, env, {})
    expect(received).toEqual({ cron: '0 */5 * * *' })
  })

  it('cron with malformed event.cron silently no-ops', async () => {
    const router = loadRouter([worker('cleaner')])
    await expect(
      router.scheduled({ cron: 'missing-separator' }, {}, {}),
    ).resolves.toBeUndefined()
    await expect(router.scheduled({ cron: '' }, {}, {})).resolves.toBeUndefined()
  })

  it('cron targeting an unknown worker silently no-ops', async () => {
    const router = loadRouter([worker('cleaner')])
    await expect(
      router.scheduled({ cron: 'nobody|* * * * *' }, {}, {}),
    ).resolves.toBeUndefined()
  })
})
