/**
 * Source text for the KV adapter Worker that runs inside workerd.
 *
 * The adapter is a Durable Object whose SqlStorage (workerd-native) backs
 * a `kv` table matching the schema in design/config.md#kv. The tenant
 * Worker reaches this via a DurableObject namespace binding, wrapped by
 * a facade shim so the tenant sees `env.<BINDING>.get/put/list` (the
 * Cloudflare KV API) rather than a raw DO stub.
 *
 * Kept as exported string constants (not .js files) so:
 *   1. The build step doesn't need to copy/bundle anything.
 *   2. Integration tests can write them verbatim to temp dirs.
 *   3. Unit tests can assert substring contents / stability.
 *
 * The JS targets workerd's runtime (compatibility_date >= 2024-04-03 so
 * DO SqlStorage is stable). It does NOT run under Node — don't try to
 * execute it from unit tests with a JS vm.
 */

import { TENANT_METRICS_SHIM_SOURCE } from '../metrics/tenant-shim-source.js'

/**
 * The KvStore Durable Object class. One instance (by `idFromName('default')`)
 * per tenant-binding pair. Exposes `kvGet / kvPut / kvDelete / kvList /
 * kvGetWithMetadata` as RPC methods the tenant-side facade calls.
 *
 * Storage strategy: workerd's DO `state.storage` API is itself a key-value
 * store with prefix-list support — exactly what CF KV needs. Each KV row
 * is stored as a single JSON envelope `{v, m, e}`:
 *   v = the byte value (Uint8Array preserved through the storage layer)
 *   m = the metadata JSON value (or null)
 *   e = expires_at unix ms (or null)
 *
 * We chose state.storage over SqlStorage because workerd's enableSql in
 * capnp-only configs has migration-history semantics that aren't available
 * outside wrangler. KV-on-KV is also the more direct mapping anyway.
 */
export const KV_ADAPTER_DO_SOURCE = String.raw`// GENERATED by groundflare.
// KV adapter Durable Object. Backs one tenant-binding pair with the
// DO state.storage key-value API.

import { DurableObject } from 'cloudflare:workers'

const MAX_LIST_LIMIT = 1000
const DEFAULT_LIST_LIMIT = 1000

export class KvStore extends DurableObject {
  async kvPut(key, value, options) {
    if (options?.expirationTtl !== undefined && options?.expiration !== undefined) {
      throw new TypeError('KV put: expirationTtl and expiration are mutually exclusive')
    }
    let expiresAt = null
    if (options?.expirationTtl !== undefined) {
      if (options.expirationTtl <= 0) {
        throw new RangeError('KV put: expirationTtl must be > 0 seconds')
      }
      expiresAt = Date.now() + options.expirationTtl * 1000
    } else if (options?.expiration !== undefined) {
      if (options.expiration <= 0) {
        throw new RangeError('KV put: expiration must be a positive unix seconds value')
      }
      expiresAt = options.expiration * 1000
    }

    const envelope = {
      v: toBytes(value),
      m: options?.metadata ?? null,
      e: expiresAt,
    }
    await this.ctx.storage.put(key, envelope)
  }

  async kvGet(key) {
    const envelope = await this.ctx.storage.get(key)
    if (!envelope) return null
    if (envelope.e !== null && envelope.e <= Date.now()) return null
    return {
      value: envelope.v,
      metadata: envelope.m,
    }
  }

  async kvDelete(key) {
    await this.ctx.storage.delete(key)
  }

  async kvList(options) {
    const prefix = options?.prefix ?? ''
    const rawLimit = options?.limit ?? DEFAULT_LIST_LIMIT
    const limit = Math.max(1, Math.min(MAX_LIST_LIMIT, Math.floor(rawLimit)))
    const cursor = options?.cursor

    // Fetch one extra row beyond the limit to detect "more available".
    const listOpts = { limit: limit + 1 }
    if (prefix) listOpts.prefix = prefix
    if (cursor) listOpts.startAfter = atob(cursor)

    const stored = await this.ctx.storage.list(listOpts)
    // stored is a Map<string, value> in insertion order = lexicographic for
    // string keys. Materialize as array, filter expired, keep first \`limit\`.
    const now = Date.now()
    const all = []
    for (const [name, env] of stored) {
      if (env.e !== null && env.e <= now) continue
      const k = { name }
      if (env.e !== null) k.expiration = Math.floor(env.e / 1000)
      if (env.m !== null) k.metadata = env.m
      all.push(k)
    }

    const hasMore = all.length > limit
    const page = hasMore ? all.slice(0, limit) : all
    const out = { keys: page, list_complete: !hasMore }
    if (hasMore) out.cursor = btoa(page[page.length - 1].name)
    return out
  }

  async kvGetWithMetadata(key) {
    const row = await this.kvGet(key)
    if (!row) return { value: null, metadata: null }
    return row
  }

  async kvCleanup() {
    const now = Date.now()
    const all = await this.ctx.storage.list()
    let removed = 0
    for (const [name, env] of all) {
      if (env.e !== null && env.e <= now) {
        await this.ctx.storage.delete(name)
        removed++
      }
    }
    return removed
  }
}

// ─── helpers ─────────────────────────────────────────────────────

function toBytes(value) {
  if (typeof value === 'string') return new TextEncoder().encode(value)
  if (value instanceof ArrayBuffer) return new Uint8Array(value)
  if (ArrayBuffer.isView(value)) {
    return new Uint8Array(value.buffer, value.byteOffset, value.byteLength)
  }
  throw new TypeError('KV put: unsupported value type')
}

// The adapter service's default export is a no-op fetch handler: the
// adapter is only reachable via the DO binding, not HTTP. Providing a
// default export keeps workerd happy when it treats the service as a
// general-purpose Worker.
export default {
  async fetch() {
    return new Response('groundflare KV adapter — DO access only', { status: 404 })
  },
}
`

/**
 * One KV binding's config as the shim needs it: name + shard count.
 * A string literal is accepted for backwards-compatibility; it maps to
 * `{ name: s, shards: 1 }`. See design/kv-sharding.md for the routing
 * algorithm and cursor format.
 */
export type KvShimBinding = string | { readonly name: string; readonly shards?: number }

function normalizeShimBinding(b: KvShimBinding): { name: string; shards: number } {
  if (typeof b === 'string') return { name: b, shards: 1 }
  const shards = b.shards ?? 1
  if (!Number.isInteger(shards) || shards < 1) {
    throw new RangeError(`KV shim: shards must be a positive integer (got ${shards} for ${b.name})`)
  }
  return { name: b.name, shards }
}

/**
 * Generate the tenant shim module source for a worker with KV bindings.
 *
 * The shim:
 *   1. Imports the user's real entry (stored alongside as `./user.js`)
 *   2. Wraps `env` so each KV binding name becomes a CF KV-compatible
 *      facade object instead of the raw DurableObjectNamespace.
 *   3. For sharded bindings (shards > 1), hash-routes single-key ops
 *      across N DO instances via FNV-1a 32-bit (see design/kv-sharding.md).
 *   4. Forwards fetch/scheduled/other handler invocations to the user module.
 */
export function generateTenantKvShim(bindings: readonly KvShimBinding[]): string {
  const normalized = bindings.map(normalizeShimBinding)
  const shardsLiteral = JSON.stringify(
    Object.fromEntries(
      normalized
        .slice()
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((b) => [b.name, b.shards]),
    ),
  )
  return String.raw`// GENERATED by groundflare — tenant shim.
// Wraps the user's Worker entry to expose DO-backed KV bindings as CF KV.

import user from './user.js'
// Re-export user's named exports so workerd can resolve DO classes
// declared on the user module (this shim is the main module; workerd
// looks up namespace class names on the main module's export set).
export * from './user.js'

${TENANT_METRICS_SHIM_SOURCE}
const KV_SHARDS = ${shardsLiteral}

function fnv1a32(s) {
  let h = 2166136261 >>> 0
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return h >>> 0
}

function shardName(binding, key) {
  const n = KV_SHARDS[binding] || 1
  if (n === 1) return 'default'
  return 'shard-' + (fnv1a32(key) % n)
}

function decodeValue(bytes, type) {
  if (type === 'arrayBuffer') {
    // Copy to a fresh ArrayBuffer so the caller can mutate/transfer.
    const copy = new Uint8Array(bytes.byteLength)
    copy.set(bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes))
    return copy.buffer
  }
  const decoded = new TextDecoder().decode(bytes)
  if (type === 'json') return JSON.parse(decoded)
  return decoded
}

function normalizeType(options) {
  if (options === undefined) return 'text'
  if (typeof options === 'string') return options
  return options.type ?? 'text'
}

function makeFacade(doNamespace, binding) {
  const stubFor = (key) => doNamespace.get(doNamespace.idFromName(shardName(binding, key)))
  return {
    async get(key, options) {
      return gf_timeKv(binding, 'get', async () => {
        const row = await stubFor(key).kvGet(key)
        if (!row) return null
        return decodeValue(row.value, normalizeType(options))
      })
    },
    async getWithMetadata(key, options) {
      return gf_timeKv(binding, 'getWithMetadata', async () => {
        const row = await stubFor(key).kvGetWithMetadata(key)
        if (!row.value) return { value: null, metadata: null }
        return {
          value: decodeValue(row.value, normalizeType(options)),
          metadata: row.metadata,
        }
      })
    },
    async put(key, value, options) {
      return gf_timeKv(binding, 'put', () => stubFor(key).kvPut(key, value, options))
    },
    async delete(key) {
      return gf_timeKv(binding, 'delete', () => stubFor(key).kvDelete(key))
    },
    async list(options) {
      return gf_timeKv(binding, 'list', async () => {
        const n = KV_SHARDS[binding] || 1
        if (n === 1) {
          return doNamespace.get(doNamespace.idFromName('default')).kvList(options)
        }
        // Phase 1 naive: iterate all shards, merge in memory, no cursor.
        // Proper composite-cursor implementation lands in Phase 2 — see
        // design/kv-sharding.md §List semantics.
        if (options && options.cursor) {
          throw new Error(
            'KV list() pagination across shards is not yet supported (Phase 2). ' +
            'Either set shards=1 or request a larger single page.',
          )
        }
        const perShard = Math.max(1, (options?.limit ?? 1000))
        const pages = await Promise.all(
          Array.from({ length: n }, (_, i) =>
            doNamespace.get(doNamespace.idFromName('shard-' + i)).kvList({ ...options, limit: perShard }),
          ),
        )
        const merged = []
        for (const page of pages) for (const k of page.keys) merged.push(k)
        merged.sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)
        const capped = merged.slice(0, perShard)
        return { keys: capped, list_complete: capped.length === merged.length }
      })
    },
  }
}

function wrapEnv(env) {
  const out = { ...env }
  for (const name of Object.keys(KV_SHARDS)) {
    const raw = out[name]
    if (raw && typeof raw.idFromName === 'function') {
      out[name] = makeFacade(raw, name)
    }
  }
  return out
}

export default {
  async fetch(request, env, ctx) {
    const internal = gf_handleInternalMetrics(request)
    if (internal) return internal
    return user.fetch(request, wrapEnv(env), ctx)
  },
  async scheduled(event, env, ctx) {
    if (user.scheduled) return user.scheduled(event, wrapEnv(env), ctx)
  },
}
`
}

/**
 * Fixed module name used by the adapter service exposing the KvStore class.
 * Used by the capnp generator to embed the source at a stable relative path.
 */
export const KV_ADAPTER_MODULE_NAME = 'worker'

/**
 * DO class name exported by the adapter service. The tenant's binding
 * refers to this by (className, serviceName) pair.
 */
export const KV_DO_CLASS_NAME = 'KvStore'
