/**
 * systemd unit generator for the Bun runtime.
 *
 * Pure text producer — no I/O. The deploy flow writes this to
 * /etc/systemd/system/groundflare-worker.service on the VPS after
 * rendering. See design/tracks.md §"Bun track" for the shape of what
 * the Bun runtime runs.
 *
 * Kept parallel to src/runtime/bootstrap/systemd.ts (workerd unit)
 * rather than merged into a polymorphic generator. The two runtimes
 * take different binaries and different entry-point shapes; a
 * single function with a discriminator would hide those differences
 * from a reader scanning for "what actually runs when I deploy Bun?"
 * The duplication is ~40 LOC and is covered by dedicated tests.
 */

export interface BunUnitOptions {
  /**
   * systemd Description= field. Recommended: "groundflare Bun runtime
   * for workspace <name>".
   */
  readonly description?: string

  /** Path to the bun binary. Default `/usr/local/bin/bun`. */
  readonly bunBinary?: string

  /**
   * Path to the Bun entry module that `bun run` will execute. Required;
   * usually `/var/lib/groundflare/server.js` — the workspace build writes
   * the compiled entry there, alongside the user's bundled modules.
   */
  readonly entryPath: string

  /**
   * EnvironmentFile path (for [vars] exposed to Bun via shell env).
   * Default `/etc/groundflare/environment`. Set to null to omit.
   */
  readonly environmentFile?: string | null

  /**
   * Working directory of the process. Default `/var/lib/groundflare`.
   */
  readonly workingDirectory?: string

  /** Unix user + group to run under. Default `groundflare`. */
  readonly user?: string
  readonly group?: string

  // ── Resource limits (systemd cgroup v2) ───────────────────────
  /** Percentage of host RAM. Default 80. */
  readonly memoryMaxPercent?: number
  /** Percentage of host CPU. Default 80. */
  readonly cpuQuotaPercent?: number
  /** Max file descriptors. Default 65536. */
  readonly limitNoFile?: number
  /** Max processes + threads. Default 1024. */
  readonly tasksMax?: number

  // ── Restart policy ────────────────────────────────────────────
  /** Default on-failure. */
  readonly restart?: 'on-failure' | 'always' | 'no'
  /** Seconds between restart attempts. Default 5. */
  readonly restartSec?: number

  /**
   * Extra raw ini lines to append to the [Service] section.
   * Useful for Hardening= directives or `Environment=` pairs the user
   * didn't want in an EnvironmentFile.
   */
  readonly extraServiceLines?: readonly string[]

  /** The [Install] WantedBy target. Default `multi-user.target`. */
  readonly wantedBy?: string
}

const DEFAULTS = {
  description: 'groundflare Bun runtime',
  bunBinary: '/usr/local/bin/bun',
  environmentFile: '/etc/groundflare/environment',
  workingDirectory: '/var/lib/groundflare',
  user: 'groundflare',
  group: 'groundflare',
  memoryMaxPercent: 80,
  cpuQuotaPercent: 80,
  limitNoFile: 65536,
  tasksMax: 1024,
  restart: 'on-failure',
  restartSec: 5,
  wantedBy: 'multi-user.target',
} as const

const SYSTEMD_HEADER =
  '# GENERATED by groundflare — do not edit by hand.\n' +
  '# Regenerated on every `groundflare deploy`; local edits will be lost.\n'

export function generateBunSystemdUnit(opts: BunUnitOptions): string {
  if (!opts.entryPath) {
    throw new TypeError('generateBunSystemdUnit: entryPath is required')
  }

  const description = opts.description ?? DEFAULTS.description
  const bunBinary = opts.bunBinary ?? DEFAULTS.bunBinary
  const envFile =
    opts.environmentFile === null
      ? null
      : (opts.environmentFile ?? DEFAULTS.environmentFile)
  const workingDirectory = opts.workingDirectory ?? DEFAULTS.workingDirectory
  const user = opts.user ?? DEFAULTS.user
  const group = opts.group ?? DEFAULTS.group

  const memoryMax = validatePercent(
    opts.memoryMaxPercent ?? DEFAULTS.memoryMaxPercent,
    'memoryMaxPercent',
  )
  const cpuQuota = validatePercent(
    opts.cpuQuotaPercent ?? DEFAULTS.cpuQuotaPercent,
    'cpuQuotaPercent',
  )
  const limitNoFile = opts.limitNoFile ?? DEFAULTS.limitNoFile
  const tasksMax = opts.tasksMax ?? DEFAULTS.tasksMax
  const restart = opts.restart ?? DEFAULTS.restart
  const restartSec = opts.restartSec ?? DEFAULTS.restartSec
  const wantedBy = opts.wantedBy ?? DEFAULTS.wantedBy

  const serviceLines: string[] = [
    'Type=simple',
    `User=${user}`,
    `Group=${group}`,
    `WorkingDirectory=${workingDirectory}`,
  ]

  // "-" prefix tells systemd to skip (not fail) when the file is missing.
  // A Worker without [vars] produces no environment file at deploy time, so
  // the unit must start cleanly without it.
  if (envFile !== null) serviceLines.push(`EnvironmentFile=-${envFile}`)

  serviceLines.push(
    `ExecStart=${bunBinary} run ${opts.entryPath}`,
    `Restart=${restart}`,
    `RestartSec=${restartSec}`,
    'StandardOutput=journal',
    'StandardError=journal',
    'SyslogIdentifier=groundflare-worker',
    `LimitNOFILE=${limitNoFile}`,
    `MemoryMax=${memoryMax}%`,
    `CPUQuota=${cpuQuota}%`,
    `TasksMax=${tasksMax}`,
  )

  if (opts.extraServiceLines && opts.extraServiceLines.length > 0) {
    serviceLines.push(...opts.extraServiceLines)
  }

  return (
    SYSTEMD_HEADER +
    '\n[Unit]\n' +
    `Description=${description}\n` +
    'After=network.target\n' +
    '\n[Service]\n' +
    serviceLines.join('\n') +
    '\n\n[Install]\n' +
    `WantedBy=${wantedBy}\n`
  )
}

function validatePercent(value: number, name: string): number {
  if (!Number.isFinite(value) || value <= 0 || value > 100) {
    throw new RangeError(`${name} must be in (0, 100]; got ${value}`)
  }
  return Math.floor(value)
}
