/**
 * Caddyfile generator.
 *
 * Caddy terminates TLS, handles Let's Encrypt ACME, emits JSON access logs
 * to journald, and reverse-proxies every configured domain to a single
 * upstream — the workerd router socket. The router worker itself decides
 * which tenant answers.
 *
 * See design/workspaces.md for the routing model (Caddy → workerd :8080
 * → Router Worker → tenant service bindings).
 */

export interface CaddySite {
  /** Hostname that terminates here. e.g. "api.example.com". Required. */
  readonly hostname: string

  /** Upstream `host:port` that Caddy reverse-proxies to. */
  readonly upstream: string

  /**
   * Enable gzip/zstd response compression. Default true — the workerd
   * router doesn't compress, and most tenant Workers don't either.
   */
  readonly encode?: boolean

  /** Extra Caddyfile directives inside the site block (raw text). */
  readonly extra?: readonly string[]
}

export interface CaddyfileOptions {
  /** ACME contact email for Let's Encrypt. Required for automatic TLS. */
  readonly email: string

  readonly sites: readonly CaddySite[]

  /**
   * Override the ACME CA. Default = Let's Encrypt production.
   * Use the staging URL during early bootstrap to avoid rate limits.
   */
  readonly acmeCa?: string

  /**
   * Default admin API address. Caddy binds to localhost:2019 by default;
   * set to null to disable entirely.
   */
  readonly adminAddress?: string | null

  /**
   * Persist_config stanza. Default true (recommended — Caddy saves its
   * active config in the OS storage dir for resume).
   */
  readonly persistConfig?: boolean
}

const GENERATED_HEADER =
  '# GENERATED by groundflare — do not edit by hand.\n' +
  '# Regenerated on every `groundflare deploy`; local edits will be lost.\n\n'

export function generateCaddyfile(opts: CaddyfileOptions): string {
  if (!isValidEmail(opts.email)) {
    throw new TypeError(`Caddyfile: invalid email address: ${opts.email}`)
  }

  for (const site of opts.sites) {
    if (!isValidHostname(site.hostname)) {
      throw new TypeError(`Caddyfile: invalid hostname: ${site.hostname}`)
    }
    if (!isValidUpstream(site.upstream)) {
      throw new TypeError(`Caddyfile: invalid upstream: ${site.upstream}`)
    }
  }

  const globalLines: string[] = [`email ${opts.email}`]
  if (opts.acmeCa !== undefined) globalLines.push(`acme_ca ${opts.acmeCa}`)
  if (opts.adminAddress === null) globalLines.push('admin off')
  else if (opts.adminAddress !== undefined)
    globalLines.push(`admin ${opts.adminAddress}`)
  if (opts.persistConfig !== false) globalLines.push('persist_config on')

  const siteBlocks = opts.sites.map(renderSite).join('\n\n')

  return (
    GENERATED_HEADER +
    '{\n' +
    globalLines.map((l) => `  ${l}`).join('\n') +
    '\n}\n' +
    (siteBlocks ? '\n' + siteBlocks + '\n' : '')
  )
}

function renderSite(site: CaddySite): string {
  const lines: string[] = [`reverse_proxy ${site.upstream}`]
  if (site.encode !== false) lines.push('encode gzip zstd')
  lines.push('log {')
  lines.push('  output stdout')
  lines.push('  format json')
  lines.push('}')
  if (site.extra && site.extra.length > 0) lines.push(...site.extra)

  return (
    `${site.hostname} {\n` +
    lines.map((l) => `  ${l}`).join('\n') +
    '\n}'
  )
}

// ─── Validation ────────────────────────────────────────────────────

function isValidEmail(value: string): boolean {
  // Minimal validation: exactly one @, non-empty on both sides, at least
  // one dot in the domain. We don't attempt RFC 5322 — ACME registration
  // will reject garbage more definitively.
  const at = value.indexOf('@')
  if (at <= 0 || at === value.length - 1) return false
  if (value.indexOf('@', at + 1) !== -1) return false
  const domain = value.slice(at + 1)
  return domain.includes('.') && !domain.startsWith('.') && !domain.endsWith('.')
}

const HOSTNAME_LABEL_RE = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/i

function isValidHostname(value: string): boolean {
  if (value.length === 0 || value.length > 253) return false
  const labels = value.split('.')
  return labels.every((label) => HOSTNAME_LABEL_RE.test(label))
}

const UPSTREAM_RE = /^[a-z0-9._:/-]+(?::\d+)?$/i

function isValidUpstream(value: string): boolean {
  return value.length > 0 && UPSTREAM_RE.test(value)
}
