/**
 * systemd unit generators for the workerd runtime.
 *
 * Pure text producers — no I/O. The deploy flow writes these to
 * /etc/systemd/system/ on the VPS after rendering. See design/bootstrap.md
 * Stage 6 for the role of each unit in the overall pipeline.
 */

import { createHash } from 'node:crypto'
import { cronToSystemdCalendar } from './cron.js'

export interface WorkerUnitOptions {
  /**
   * systemd Description= field. Recommended: "groundflare workerd runtime
   * for workspace <name>".
   */
  readonly description?: string

  /** Path to the workerd binary. Default `/usr/local/bin/workerd`. */
  readonly workerdBinary?: string

  /**
   * Path to the capnp config that workerd should load. Required; usually
   * `/var/lib/groundflare/worker.capnp` (the capnp file's `embed` paths
   * resolve relative to the file, so keeping it at the base of
   * /var/lib/groundflare lines up with the tenant bundle layout).
   */
  readonly capnpPath: string

  /**
   * EnvironmentFile path (for [vars] exposed to workerd via shell env).
   * Default `/etc/groundflare/environment`. Set to null to omit.
   */
  readonly environmentFile?: string | null

  /**
   * Working directory of the process. Default `/var/lib/groundflare`.
   */
  readonly workingDirectory?: string

  /** Unix user + group to run under. Default `groundflare`. */
  readonly user?: string
  readonly group?: string

  // ── Resource limits (systemd cgroup v2) ───────────────────────
  /** Percentage of host RAM. Default 80. */
  readonly memoryMaxPercent?: number
  /** Percentage of host CPU. Default 80. */
  readonly cpuQuotaPercent?: number
  /** Max file descriptors. Default 65536. */
  readonly limitNoFile?: number
  /** Max processes + threads. Default 1024. */
  readonly tasksMax?: number

  // ── Restart policy ────────────────────────────────────────────
  /** Default on-failure. */
  readonly restart?: 'on-failure' | 'always' | 'no'
  /** Seconds between restart attempts. Default 5. */
  readonly restartSec?: number

  /**
   * Extra raw ini lines to append to the [Service] section.
   * Useful for Hardening= directives or `Environment=` pairs the user
   * didn't want in an EnvironmentFile.
   */
  readonly extraServiceLines?: readonly string[]

  /** The [Install] WantedBy target. Default `multi-user.target`. */
  readonly wantedBy?: string
}

const DEFAULTS = {
  description: 'groundflare workerd runtime',
  workerdBinary: '/usr/local/bin/workerd',
  environmentFile: '/etc/groundflare/environment',
  workingDirectory: '/var/lib/groundflare',
  user: 'groundflare',
  group: 'groundflare',
  memoryMaxPercent: 80,
  cpuQuotaPercent: 80,
  limitNoFile: 65536,
  tasksMax: 1024,
  restart: 'on-failure',
  restartSec: 5,
  wantedBy: 'multi-user.target',
} as const

const SYSTEMD_HEADER =
  '# GENERATED by groundflare — do not edit by hand.\n' +
  '# Regenerated on every `groundflare deploy`; local edits will be lost.\n'

export function generateWorkerSystemdUnit(opts: WorkerUnitOptions): string {
  const description = opts.description ?? DEFAULTS.description
  const workerdBinary = opts.workerdBinary ?? DEFAULTS.workerdBinary
  const envFile =
    opts.environmentFile === null
      ? null
      : (opts.environmentFile ?? DEFAULTS.environmentFile)
  const workingDirectory = opts.workingDirectory ?? DEFAULTS.workingDirectory
  const user = opts.user ?? DEFAULTS.user
  const group = opts.group ?? DEFAULTS.group

  const memoryMax = validatePercent(
    opts.memoryMaxPercent ?? DEFAULTS.memoryMaxPercent,
    'memoryMaxPercent',
  )
  const cpuQuota = validatePercent(
    opts.cpuQuotaPercent ?? DEFAULTS.cpuQuotaPercent,
    'cpuQuotaPercent',
  )
  const limitNoFile = opts.limitNoFile ?? DEFAULTS.limitNoFile
  const tasksMax = opts.tasksMax ?? DEFAULTS.tasksMax
  const restart = opts.restart ?? DEFAULTS.restart
  const restartSec = opts.restartSec ?? DEFAULTS.restartSec
  const wantedBy = opts.wantedBy ?? DEFAULTS.wantedBy

  const serviceLines: string[] = [
    'Type=simple',
    `User=${user}`,
    `Group=${group}`,
    `WorkingDirectory=${workingDirectory}`,
  ]

  // "-" prefix tells systemd to skip (not fail) when the file is missing.
  // A Worker without [vars] produces no environment file at deploy time, so
  // the unit must start cleanly without it.
  if (envFile !== null) serviceLines.push(`EnvironmentFile=-${envFile}`)

  serviceLines.push(
    `ExecStart=${workerdBinary} serve ${opts.capnpPath}`,
    `Restart=${restart}`,
    `RestartSec=${restartSec}`,
    'StandardOutput=journal',
    'StandardError=journal',
    'SyslogIdentifier=groundflare-worker',
    `LimitNOFILE=${limitNoFile}`,
    `MemoryMax=${memoryMax}%`,
    `CPUQuota=${cpuQuota}%`,
    `TasksMax=${tasksMax}`,
  )

  if (opts.extraServiceLines && opts.extraServiceLines.length > 0) {
    serviceLines.push(...opts.extraServiceLines)
  }

  return (
    SYSTEMD_HEADER +
    '\n[Unit]\n' +
    `Description=${description}\n` +
    'After=network.target\n' +
    '\n[Service]\n' +
    serviceLines.join('\n') +
    '\n\n[Install]\n' +
    `WantedBy=${wantedBy}\n`
  )
}

function validatePercent(value: number, name: string): number {
  if (!Number.isFinite(value) || value <= 0 || value > 100) {
    throw new RangeError(`${name} must be in (0, 100]; got ${value}`)
  }
  return Math.floor(value)
}

// ─── Cron timer / service units ────────────────────────────────────

export interface CronUnitOptions {
  /** Worker name that owns this cron entry. Required. */
  readonly workerName: string

  /** Five-field cron expression. Required. */
  readonly cronExpression: string

  /**
   * systemd `Persistent=` — when true, a missed trigger during downtime
   * fires immediately on next boot. Default true. See design/bootstrap.md.
   */
  readonly persistent?: boolean

  /**
   * Accuracy of trigger firing. Default `1s` (tight; matches CF's edge
   * scheduler expectations). Looser values allow systemd to batch timer
   * firings on low-power systems.
   */
  readonly accuracy?: string

  /**
   * URL the service's curl hits to dispatch the event. Default
   * `http://127.0.0.1:8080/__scheduled` — the Router Worker's internal
   * scheduled endpoint. The worker name and cron are passed as query
   * parameters so the router can route to the right tenant.
   */
  readonly scheduledEndpoint?: string

  /**
   * Service the cron service requires before dispatching (so we don't
   * curl a worker that hasn't started yet). Default
   * `groundflare-worker.service`.
   */
  readonly requiresUnit?: string
}

export interface CronUnitPair {
  /**
   * Stable unit filename stem (e.g. `groundflare-cron-api-8f3c9e1a`).
   * Append `.timer` for the timer, `.service` for the service.
   */
  readonly unitName: string
  readonly timer: string
  readonly service: string
}

const CRON_DEFAULT_ENDPOINT = 'http://127.0.0.1:8080/__scheduled'
const CRON_DEFAULT_REQUIRES = 'groundflare-worker.service'
const CRON_DEFAULT_ACCURACY = '1s'

/**
 * Produce the `.timer` + `.service` pair for a single cron entry.
 *
 * The unit name is deterministic: a short hash of (worker, expression)
 * so redeploys produce stable filenames and systemctl identifiers.
 */
export function generateCronUnitPair(opts: CronUnitOptions): CronUnitPair {
  validateWorkerName(opts.workerName)
  const onCalendar = cronToSystemdCalendar(opts.cronExpression)
  const unitName = cronUnitName(opts.workerName, opts.cronExpression)
  const persistent = opts.persistent !== false
  const accuracy = opts.accuracy ?? CRON_DEFAULT_ACCURACY
  const endpoint = opts.scheduledEndpoint ?? CRON_DEFAULT_ENDPOINT
  const requires = opts.requiresUnit ?? CRON_DEFAULT_REQUIRES

  const queryString = buildQueryString({
    worker: opts.workerName,
    cron: opts.cronExpression,
  })
  const dispatchUrl = `${endpoint}?${queryString}`

  const timer =
    SYSTEMD_HEADER +
    '\n[Unit]\n' +
    `Description=groundflare cron: ${opts.workerName} @ ${opts.cronExpression}\n` +
    '\n[Timer]\n' +
    `OnCalendar=${onCalendar}\n` +
    `AccuracySec=${accuracy}\n` +
    (persistent ? 'Persistent=true\n' : 'Persistent=false\n') +
    `Unit=${unitName}.service\n` +
    '\n[Install]\n' +
    'WantedBy=timers.target\n'

  const service =
    SYSTEMD_HEADER +
    '\n[Unit]\n' +
    `Description=groundflare cron dispatch: ${opts.workerName} @ ${opts.cronExpression}\n` +
    `Requires=${requires}\n` +
    `After=${requires}\n` +
    '\n[Service]\n' +
    'Type=oneshot\n' +
    `ExecStart=/usr/bin/curl --silent --show-error --fail --max-time 30 ` +
    `--request POST ${shellSingleQuote(dispatchUrl)}\n` +
    'StandardOutput=journal\n' +
    'StandardError=journal\n' +
    `SyslogIdentifier=${unitName}\n`

  return { unitName, timer, service }
}

/**
 * Deterministic unit stem for a (worker, expression) pair. Stable across
 * redeploys so systemd's state tracking (last-trigger time for Persistent=)
 * survives.
 */
export function cronUnitName(workerName: string, cronExpression: string): string {
  const hash = createHash('sha256')
    .update(`${workerName}\0${cronExpression}`)
    .digest('hex')
    .slice(0, 8)
  return `groundflare-cron-${workerName}-${hash}`
}

function validateWorkerName(name: string): void {
  if (!/^[a-z][a-z0-9-]{0,39}$/.test(name)) {
    throw new TypeError(
      `systemd cron: invalid worker name ${JSON.stringify(name)}; ` +
        `must match /^[a-z][a-z0-9-]{0,39}$/`,
    )
  }
}

function buildQueryString(params: Record<string, string>): string {
  const parts: string[] = []
  for (const [k, v] of Object.entries(params)) {
    parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(v)}`)
  }
  return parts.join('&')
}

function shellSingleQuote(value: string): string {
  // Wrap in single quotes and replace any embedded single quote with
  // the safe "'\''" sequence. Our known inputs (URLs built from
  // encodeURIComponent) never actually contain single quotes, but the
  // guard is cheap and makes the template robust.
  return `'${value.replace(/'/g, `'\\''`)}'`
}
