/**
 * Router Worker generator.
 *
 * groundflare generates the Router Worker at every deploy — it's not
 * user code. The Router sits at the single workerd socket and dispatches
 * requests to tenant Workers by Host header (via service bindings).
 *
 * Keeps the body small and exhaustively tested because a bug here takes
 * down the entire workspace. Edge cases covered in the body + unit tests:
 *   - Missing or malformed Host
 *   - Host with port (strip)
 *   - Uppercase Host (lowercase normalization)
 *   - Target Worker missing (should not happen at runtime, but defensive)
 *   - Cron dispatch via `event.cron = "<worker>|<expression>"`
 *
 * Internal paths (v0.6, observability theme):
 *   - `/__health`    — liveness; returns `{status, uptime_seconds, version}`.
 *                       Public: Caddy probes this without a Host header.
 *   - `/__metrics`   — Prometheus text-format; loopback-only (same gate
 *                       as /__scheduled).
 *   - `/__scheduled` — cron dispatch; loopback-only.
 *
 * The Router records request count + latency + error count per tenant
 * worker. Binding-level metrics (KV/D1/R2 op counts) happen inside
 * tenant isolates and are a separate emit path — deferred to a later
 * observability milestone.
 *
 * Per design/workspaces.md: not user-extensible in v0.2. Regenerated on
 * every `groundflare deploy` from the workspace manifest.
 */

import type { WorkspaceWorker } from './types.js'

/**
 * Map a worker name to the env binding the router sees it as.
 * Example: "api-gateway" → "WORKER_API_GATEWAY"
 */
export function routerBindingName(workerName: string): string {
  return 'WORKER_' + workerName.toUpperCase().replace(/-/g, '_')
}

export interface RouterGenerationInfo {
  /** Workers with a domain — included in the Host→binding map. */
  readonly routableWorkers: readonly WorkspaceWorker[]
  /** Every worker, for scheduled() cron dispatch (whether or not they're routable). */
  readonly allWorkers: readonly WorkspaceWorker[]
}

export function collectRouterInfo(workers: readonly WorkspaceWorker[]): RouterGenerationInfo {
  return {
    routableWorkers: workers.filter((w) => w.domain !== undefined),
    allWorkers: workers,
  }
}

/**
 * One service binding on the Router to fan out `/__gf_metrics` scrapes
 * against when a client hits the Router's `/__metrics`. Tenant shims
 * (KV/D1) and R2 adapters both respond to the `gf-internal` host; each
 * gets one entry here.
 */
export interface InternalScrapeTarget {
  /** env binding name on the Router, e.g. `WORKER_API` or `METRICS_R2_API_MEDIA`. */
  readonly bindingName: string
  /**
   * User-facing descriptor used only in error/telemetry lines —
   * worker name for tenant shims, `<worker>:<binding>` for R2
   * adapters.
   */
  readonly label: string
}

export interface GenerateRouterOptions {
  /**
   * Version string surfaced on `/__health`. Typically the groundflare
   * CLI version; defaults to "unknown" when not provided so the field
   * always exists in the response body.
   */
  readonly version?: string
  /**
   * Additional service bindings the Router should scrape on
   * `/__metrics` fan-out. Concatenated (in order) after the Router's
   * own series.
   */
  readonly scrapeTargets?: readonly InternalScrapeTarget[]
}

/**
 * Produce the Router Worker's ES module source text. The JS is written
 * verbatim into the capnp output as an inline `esModule`, so the code is
 * dependency-free and expects nothing outside V8 + workerd's standard APIs.
 */
export function generateRouterJs(
  workers: readonly WorkspaceWorker[],
  opts: GenerateRouterOptions = {},
): string {
  const info = collectRouterInfo(workers)
  const version = opts.version ?? 'unknown'
  const scrapeTargets = opts.scrapeTargets ?? []

  const routeLines = info.routableWorkers.map((w) => {
    const host = JSON.stringify(w.domain!.toLowerCase())
    const binding = JSON.stringify(routerBindingName(w.name))
    return `  ${host}: ${binding},`
  })

  const cronBindings = info.allWorkers.map((w) => {
    return `  ${JSON.stringify(w.name)}: ${JSON.stringify(routerBindingName(w.name))},`
  })

  // Reverse lookup: binding name → worker name. Used at dispatch time
  // so metric labels use the user-facing worker name, not the derived
  // env-binding name.
  const bindingToWorker = info.allWorkers.map((w) => {
    return `  ${JSON.stringify(routerBindingName(w.name))}: ${JSON.stringify(w.name)},`
  })

  const scrapeTargetLines = scrapeTargets.map((t) => {
    return `  { bindingName: ${JSON.stringify(t.bindingName)}, label: ${JSON.stringify(t.label)} },`
  })

  return `// GENERATED by groundflare — do not edit by hand.
// Router dispatches tenant traffic by Host header; regenerated on every
// \`groundflare deploy\`. See design/workspaces.md#router-worker.

const ROUTES = {
${routeLines.join('\n')}
}

const CRON_BINDINGS = {
${cronBindings.join('\n')}
}

const BINDING_TO_WORKER = {
${bindingToWorker.join('\n')}
}

// Fan-out list for /__metrics — each entry is a service binding the
// Router fetches with hostname "gf-internal" and path "/__gf_metrics".
// Tenant shims (KV/D1) and R2 adapters respond with their own Prom
// text; the Router concatenates all of it into one response.
const INTERNAL_SCRAPE_TARGETS = [
${scrapeTargetLines.join('\n')}
]

const VERSION = ${JSON.stringify(version)}
const BOOT_TIME_MS = Date.now()

// ─── Metrics (router-level, Prometheus text format) ───────────────
//
// Inlined rather than imported so the router stays a single
// self-contained ES module in the capnp. The TS registry at
// src/runtime/metrics/ is the reference implementation + unit-tested;
// this keeps shape-compatible output without cross-module plumbing.

const LATENCY_BUCKETS = [
  0.001, 0.002, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10,
]

// Separate maps per metric so series lookup is a single hash hit.
const REQS_BY_STATUS = new Map() // key "worker|status_class" → count
const REQ_LATENCY = new Map()     // key worker              → { counts[], sum, count }
const ERRORS_BY_KIND = new Map()  // key "worker|kind"       → count

function statusClass(status) {
  if (status >= 500) return '5xx'
  if (status >= 400) return '4xx'
  if (status >= 300) return '3xx'
  if (status >= 200) return '2xx'
  return '1xx'
}

function recordRequest(worker, status, durationMs) {
  const sc = statusClass(status)
  const reqKey = worker + '|' + sc
  REQS_BY_STATUS.set(reqKey, (REQS_BY_STATUS.get(reqKey) || 0) + 1)

  let hist = REQ_LATENCY.get(worker)
  if (!hist) {
    hist = {
      counts: new Array(LATENCY_BUCKETS.length).fill(0),
      sum: 0,
      count: 0,
    }
    REQ_LATENCY.set(worker, hist)
  }
  const durSec = durationMs / 1000
  hist.sum += durSec
  hist.count += 1
  for (let i = 0; i < LATENCY_BUCKETS.length; i++) {
    if (durSec <= LATENCY_BUCKETS[i]) hist.counts[i] += 1
  }
}

function recordError(worker, kind) {
  const key = worker + '|' + kind
  ERRORS_BY_KIND.set(key, (ERRORS_BY_KIND.get(key) || 0) + 1)
}

function escapeLabel(v) {
  return String(v).replace(/\\\\/g, '\\\\\\\\').replace(/"/g, '\\\\"').replace(/\\n/g, '\\\\n')
}

function renderMetrics() {
  const lines = []

  lines.push('# HELP groundflare_worker_requests_total Router-observed request count per worker + status class')
  lines.push('# TYPE groundflare_worker_requests_total counter')
  for (const [key, value] of REQS_BY_STATUS) {
    const sepIdx = key.indexOf('|')
    const worker = key.slice(0, sepIdx)
    const sc = key.slice(sepIdx + 1)
    lines.push(
      'groundflare_worker_requests_total{status_class="' + escapeLabel(sc) +
        '",worker="' + escapeLabel(worker) + '"} ' + value,
    )
  }

  lines.push('# HELP groundflare_worker_request_duration_seconds Router-observed request latency per worker')
  lines.push('# TYPE groundflare_worker_request_duration_seconds histogram')
  for (const [worker, hist] of REQ_LATENCY) {
    const w = escapeLabel(worker)
    for (let i = 0; i < LATENCY_BUCKETS.length; i++) {
      lines.push(
        'groundflare_worker_request_duration_seconds_bucket{le="' +
          LATENCY_BUCKETS[i] + '",worker="' + w + '"} ' + hist.counts[i],
      )
    }
    lines.push(
      'groundflare_worker_request_duration_seconds_bucket{le="+Inf",worker="' + w + '"} ' + hist.count,
    )
    lines.push('groundflare_worker_request_duration_seconds_sum{worker="' + w + '"} ' + hist.sum)
    lines.push('groundflare_worker_request_duration_seconds_count{worker="' + w + '"} ' + hist.count)
  }

  lines.push('# HELP groundflare_worker_errors_total Router-observed errors per worker + kind')
  lines.push('# TYPE groundflare_worker_errors_total counter')
  for (const [key, value] of ERRORS_BY_KIND) {
    const sepIdx = key.indexOf('|')
    const worker = key.slice(0, sepIdx)
    const kind = key.slice(sepIdx + 1)
    lines.push(
      'groundflare_worker_errors_total{kind="' + escapeLabel(kind) +
        '",worker="' + escapeLabel(worker) + '"} ' + value,
    )
  }

  return lines.join('\\n') + '\\n'
}

function renderHealth() {
  return JSON.stringify({
    status: 'ok',
    uptime_seconds: Math.floor((Date.now() - BOOT_TIME_MS) / 1000),
    version: VERSION,
  })
}

// ─── Handlers ─────────────────────────────────────────────────────

function plain(body, status) {
  return new Response(body, {
    status,
    headers: { 'content-type': 'text/plain; charset=utf-8' },
  })
}

// Fan out /__gf_metrics scrapes against every registered target, in
// parallel. A target that throws, times out, or returns non-200 gets a
// commented stub in the output — never an aborted scrape. The comment
// lets operators see in the raw text which target misbehaved without
// the CLI parser having to know about it.
async function collectInternalMetrics(env, ctx) {
  if (INTERNAL_SCRAPE_TARGETS.length === 0) return ''
  const INTERNAL_URL = 'http://gf-internal/__gf_metrics'
  const pieces = await Promise.all(
    INTERNAL_SCRAPE_TARGETS.map(async (target) => {
      const binding = env[target.bindingName]
      if (!binding || typeof binding.fetch !== 'function') {
        return '# scrape ' + target.label + ': binding missing\\n'
      }
      try {
        const resp = await binding.fetch(new Request(INTERNAL_URL))
        if (resp.status !== 200) {
          return '# scrape ' + target.label + ': HTTP ' + resp.status + '\\n'
        }
        return await resp.text()
      } catch (err) {
        const msg = err && err.message ? err.message : String(err)
        return '# scrape ' + target.label + ': ' + msg + '\\n'
      }
    }),
  )
  // Separator comment keeps the concatenated output grep-friendly.
  return pieces.join('')
}

async function dispatchScheduled(url, env) {
  if (url.hostname !== '127.0.0.1' && url.hostname !== 'localhost') {
    return plain('not found', 404)
  }
  const workerName = url.searchParams.get('worker')
  if (!workerName) return plain('missing worker parameter', 400)
  const bindingName = CRON_BINDINGS[workerName]
  if (!bindingName) return plain('unknown worker: ' + workerName, 404)
  const target = env[bindingName]
  if (!target || typeof target.scheduled !== 'function') {
    return plain('target has no scheduled handler', 404)
  }
  const cron = url.searchParams.get('cron') || ''
  // Only pass the event itself across the service-binding boundary. env/ctx
  // are not serializable across workers without the experimental compat flag
  // and the target gets its own runtime env anyway.
  await target.scheduled({ cron, scheduledTime: Date.now() })
  return plain('ok', 200)
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)

    // /__health — public liveness; Caddy probes this without a Host
    // header. Cheap, no metric cost, no sensitive info.
    if (url.pathname === '/__health') {
      return new Response(renderHealth(), {
        status: 200,
        headers: { 'content-type': 'application/json; charset=utf-8' },
      })
    }

    // /__metrics — loopback-only (same gate as /__scheduled). Scraper
    // reaches it via \`groundflare status\` over SSH + curl, which
    // hits 127.0.0.1:8080 directly bypassing Caddy.
    //
    // The response concatenates router-level series with every
    // registered tenant shim / R2 adapter's /__gf_metrics body, so a
    // single scrape surfaces both the request-path view and the
    // binding-path view.
    if (url.pathname === '/__metrics') {
      if (url.hostname !== '127.0.0.1' && url.hostname !== 'localhost') {
        return plain('not found', 404)
      }
      const own = renderMetrics()
      const fanOut = await collectInternalMetrics(env, ctx)
      return new Response(own + fanOut, {
        status: 200,
        headers: { 'content-type': 'text/plain; version=0.0.4; charset=utf-8' },
      })
    }

    // Internal cron dispatch: systemd .timer units curl POST this path.
    // Gated on hostname = 127.0.0.1/localhost; external requests for the
    // same path get a plain 404 (no information leak about the feature).
    if (url.pathname === '/__scheduled') {
      if (request.method !== 'POST') {
        return new Response('method not allowed', {
          status: 405,
          headers: { allow: 'POST', 'content-type': 'text/plain; charset=utf-8' },
        })
      }
      return dispatchScheduled(url, env)
    }

    // Normal host-based dispatch to tenant Workers.
    const hostname = url.hostname.toLowerCase()
    const bindingName = ROUTES[hostname]
    if (!bindingName) {
      return plain('groundflare: no Worker matches host ' + hostname, 404)
    }
    const target = env[bindingName]
    if (!target) {
      return plain('groundflare: target binding missing for ' + bindingName, 503)
    }
    const workerName = BINDING_TO_WORKER[bindingName] || bindingName

    const start = Date.now()
    let response
    try {
      response = await target.fetch(request)
    } catch (err) {
      recordRequest(workerName, 500, Date.now() - start)
      recordError(workerName, 'uncaught')
      throw err
    }
    recordRequest(workerName, response.status, Date.now() - start)
    return response
  },
}
`
}
